"""
species.py -- the staked species of ELEMENTS-1, their grids, and the derivation
of each one's ground Sz.

GROUND Sz IS DERIVED, NOT ASSUMED.  Every Sz sector allowed by the electron
count and the orbital count is solved, and the ground total spin is read off the
degeneracy pattern: a multiplet of total spin S appears, with the same energy,
in every sector with |Sz| <= S and in none above, so

        S  =  max { Sz : E_min(Sz) = E_min(global) }.

The FCI is then run in the Sz = 0 sector for even electron counts and Sz = 1/2
for odd ones (the smallest sector that still contains the ground multiplet),
and the derived S is recorded with the energies of every sector that produced
it, so the reader can check the derivation rather than trust the label.

GRIDS ARE A DESIGN CHOICE, STAKED BEFORE THE ENERGIES ARE SEEN, not a result.
The ranges below are chosen wide enough to contain the repulsive wall and to
reach the separated-atom limit; nothing about where a minimum falls, or whether
one exists at all, is put in by hand.

Density differs between species, and the reason is compute, not physics: a
14400-determinant point costs about 950 seconds at the working precision, so the
three expensive species carry far fewer geometries than the cheap ones.  Li2 was
staked and largely computed before that cost was measured and keeps its denser
grid; N2 and CO carry a coarser base with the well window split more finely,
which is where the density actually earns its keep.  The per-species grid is
recorded in the artifact, so nothing about it is implicit.
"""

from mpmath import mpf

import curve

# (Z1, Z2, R_min, R_max, n_base, well window, splits, comment)
DIATOMICS = {
    "H2":  dict(Z1=1,  Z2=1,  rmin="0.30", rmax="10.0", nbase=110,
                well=("1.0", "2.2"),  nsplit=2, heavy=False,
                note="regression against the banked H2 referee"),
    "LiH": dict(Z1=3,  Z2=1,  rmin="1.20", rmax="14.0", nbase=90,
                well=("2.2", "4.2"),  nsplit=2, heavy=False, routeC="spot"),
    "Li2": dict(Z1=3,  Z2=3,  rmin="2.60", rmax="18.0", nbase=34,
                well=("4.2", "7.0"),  nsplit=1, heavy=True, routeC="none"),
    "HF":  dict(Z1=9,  Z2=1,  rmin="0.90", rmax="10.0", nbase=90,
                well=("1.4", "2.4"),  nsplit=2, heavy=False),
    "N2":  dict(Z1=7,  Z2=7,  rmin="1.40", rmax="9.0",  nbase=20,
                well=("1.8", "2.8"),  nsplit=2, heavy=True, routeC="none",
                sparse=dict(well_stride=2, tail_stride=3)),
    "F2":  dict(Z1=9,  Z2=9,  rmin="1.60", rmax="10.0", nbase=80,
                well=("2.0", "3.6"),  nsplit=2, heavy=False),
    "CO":  dict(Z1=6,  Z2=8,  rmin="1.40", rmax="9.0",  nbase=20,
                well=("1.9", "2.9"),  nsplit=2, heavy=True, routeC="none",
                sparse=dict(well_stride=2, tail_stride=3)),
    "He2": dict(Z1=2,  Z2=2,  rmin="1.20", rmax="12.0", nbase=100,
                well=("3.5", "8.0"),  nsplit=1, heavy=False,
                note="NEGATIVE CONTROL: closed shell, must not bind"),
    "Ne2": dict(Z1=10, Z2=10, rmin="1.80", rmax="12.0", nbase=100,
                well=("4.5", "9.0"),  nsplit=1, heavy=False,
                note="NEGATIVE CONTROL: closed shell, must not bind"),
}

ATOMS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Well-depth ordering staked by gate E2, deepest first.
E2_ORDER = ["N2", "CO", "HF", "Li2", "LiH", "F2"]
E2_UNBOUND = ["He2", "Ne2"]


GRID_DPS = 60


def sparse_subset(grid, well, spec):
    """Decimate a staked grid to a sparse STAKED SUBSET.

    THE RULE, STATED IN ADVANCE AND USING ONLY STAKED DESIGN PARAMETERS.  Keep
    a grid point when its index is divisible by a stride -- every second point
    inside the staked well window, every third outside it -- and always keep the
    first and last point so the repulsive wall and the separated-atom limit are
    both present.  The well window is itself a design input frozen before any
    energy was computed, so nothing here consults a result: the subset is a
    function of the grid rule and the window alone, and can be regenerated by
    anyone from those two.  It is manifestly not a choice of which points to
    show.

    WHY A SUBSET AT ALL.  A 14400-determinant geometry costs about 950 seconds
    at the working precision, and N2 and CO are the two species where that is
    unaffordable at full grid density on a shared machine.  The response is to
    take FEWER points, never cheaper ones: every emitted point is the same
    exact-in-model full CI in the same 14400-determinant space at the same 50
    digits, dual-route and certified.  A sparse exact referee is a referee; a
    dense approximate one is not.
    """
    from mpmath import mp as _mp
    lo, hi = mpf(well[0]), mpf(well[1])
    keep = {0, len(grid) - 1}
    for i, rs in enumerate(grid):
        r = mpf(rs)
        stride = (spec["well_stride"] if lo <= r <= hi
                  else spec["tail_stride"])
        if i % stride == 0:
            keep.add(i)
    return [grid[i] for i in sorted(keep)]


def grid_for(name):
    """The staked grid.  Built at a pinned precision so that the same species
    yields the same grid whatever precision the caller happens to be in --
    otherwise a stencil worker at dps 95 and an assembler at dps 60 would
    disagree about where the points are."""
    from mpmath import mp as _mp
    d = DIATOMICS[name]
    old = _mp.dps
    _mp.dps = GRID_DPS
    try:
        g = curve.build_grid(d["rmin"], d["rmax"], d["nbase"], d["well"],
                             d["nsplit"])
        if d.get("sparse"):
            g = sparse_subset(g, d["well"], d["sparse"])
        return g
    finally:
        _mp.dps = old


def sz_sectors(nelec, norb):
    """Every Sz sector the electron and orbital counts allow, as (2Sz, na, nb)."""
    out = []
    for two_sz in range(nelec % 2, nelec + 1, 2):
        na = (nelec + two_sz) // 2
        nb = nelec - na
        if na > norb or nb < 0 or nb > norb:
            continue
        out.append((two_sz, na, nb))
    return out


def ground_spin_from_sectors(energies, tol):
    """S = max{Sz : E_min(Sz) = E_min(global)}, as 2S.

    energies: {two_sz: E}.  tol: the degeneracy tolerance (the certified
    eigenvalue accuracy, not a fudge factor).
    """
    emin = min(energies.values())
    hit = [k for k, v in energies.items() if abs(v - emin) <= tol]
    return max(hit), emin, sorted(hit)
