//! The channel ledger's receipt scenes and readings (`tests/channel_ledger.rs`,
//! `examples/channel_receipt.rs`). Included by `#[path]` from both, so the receipt is
//! WRITTEN and CHECKED on the same atoms, the same steps, and the same readings.
//!
//! Only APIs that predate `channel.rs` are used here: the receipt is generated by the
//! engine AS IT STOOD before the channel ledger existed, and the gate is that the engine
//! after it reproduces every bit. Adding a reading that needs the new module would make
//! the receipt unwritable at the commit it exists to freeze.

use holon_chem::elements::{HYDROGEN, OXYGEN};
use holon_chem::embed::{water_centers};
use holon_render::field::{WATER_PIN_R_BOHR, WATER_PIN_THETA_RAD};
use holon_render::longrange::{CurveTail, FarSector};
use holon_render::sim::{Boundary, Dims, Sim};
use std::fmt::Write as _;

#[path = "quartet.rs"]
#[allow(dead_code)]
pub mod quartet;

pub const SUBSTEPS: u32 = 16;
/// The four-water scene's steps (FIELD-1's own count).
pub const WATER_STEPS: usize = 2000;
/// The quartet scene's steps.
pub const QUARTET_STEPS: usize = 256;

/// FIELD-1's four-water scene, verbatim from `tests/field.rs`: four waters at EMBED-1's
/// pin on a square, walled, seeded momentum-free velocities from an LCG.
pub fn four_waters(boundary: Boundary) -> Box<Sim> {
    let mono = water_centers(WATER_PIN_R_BOHR, WATER_PIN_THETA_RAD);
    let oxygens = [[5.0, 5.0, 5.0], [12.0, 5.0, 5.0], [5.0, 12.0, 5.0], [12.0, 12.0, 5.0]];
    let mut species = Vec::new();
    let mut pos = Vec::new();
    for (k, o) in oxygens.iter().enumerate() {
        let flip = if k % 2 == 0 { 1.0 } else { -1.0 };
        for (m, c) in mono.iter().enumerate() {
            species.push(if m == 0 { OXYGEN } else { HYDROGEN });
            pos.push([o[0] + flip * c[0], o[1] + c[2], o[2] + c[1]]);
        }
    }
    let mut s = quartet::scene(&species, &pos, false);
    s.dims = Dims::Three;
    s.boundary = boundary;
    s.width = 17.0;
    s.height = 17.0;
    s.depth = 10.0;
    let mut st: u64 = 0x4649_454c;
    let mut lcg = || {
        st = st.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        ((st >> 11) as f64) / ((1u64 << 53) as f64)
    };
    let n = s.n;
    let (mut px, mut py, mut pz) = (0.0, 0.0, 0.0);
    for i in 0..n {
        let scale = if s.atoms[i].species.z == 8 { 2.5e-4 } else { 1.0e-3 };
        s.atoms[i].vx = scale * (2.0 * lcg() - 1.0);
        s.atoms[i].vy = scale * (2.0 * lcg() - 1.0);
        s.atoms[i].vz = scale * (2.0 * lcg() - 1.0);
        let m = s.atoms[i].mass();
        px += m * s.atoms[i].vx;
        py += m * s.atoms[i].vy;
        pz += m * s.atoms[i].vz;
    }
    let mtot: f64 = (0..n).map(|i| s.atoms[i].mass()).sum();
    for i in 0..n {
        s.atoms[i].vx -= px / mtot;
        s.atoms[i].vy -= py / mtot;
        s.atoms[i].vz -= pz / mtot;
    }
    s.sync_species();
    s.adopt_table_timescale();
    s.rebase();
    s
}

pub fn run(s: &mut Sim, steps: usize) {
    for _ in 0..steps / SUBSTEPS as usize {
        s.step_frame(SUBSTEPS);
    }
}

/// A pure power-law curve tail, `tests/b2_longrange.rs`'s fixture.
pub fn power(p: f64, r_max: f64) -> CurveTail {
    let n = 40usize;
    let r: Vec<f64> = (0..n).map(|k| 4.0 + (r_max - 4.0) * k as f64 / (n - 1) as f64).collect();
    let u: Vec<f64> = r.iter().map(|x| -x.powf(-p)).collect();
    CurveTail { hi_b: p / r_max, r, u, solver_exit: "Converged", solver_budget_iterations: 5000, uncertainty_hartree: 1.0e-11 }
}

pub const FLOORS: [f64; 3] = [1.0e-6, 1.0e-8, 1.0e-10];
pub const BUDGETS: [f64; 3] = [1.0e-9, 1.0e-7, 1.0e-5];
pub const POWERS: [f64; 2] = [6.0, 5.5];

fn bits(out: &mut String, key: &str, v: f64) {
    let _ = writeln!(out, "{key}={:016x}", v.to_bits());
}

/// Every row, the sums, the digest, and the receipts of one scene, as raw bits.
pub fn scene_reading(out: &mut String, tag: &str, s: &Sim) {
    bits(out, &format!("{tag}.e_kin"), s.e_kin);
    bits(out, &format!("{tag}.e_pair"), s.e_pair);
    bits(out, &format!("{tag}.e_three"), s.e_three);
    bits(out, &format!("{tag}.e_many"), s.e_many);
    bits(out, &format!("{tag}.e_far"), s.e_far);
    bits(out, &format!("{tag}.e_field"), s.e_field);
    bits(out, &format!("{tag}.e_wall"), s.e_wall);
    bits(out, &format!("{tag}.e_spring"), s.e_spring);
    bits(out, &format!("{tag}.e_grav"), s.e_grav);
    bits(out, &format!("{tag}.energy"), s.energy());
    bits(out, &format!("{tag}.ledger"), s.ledger());
    bits(out, &format!("{tag}.w_ext"), s.w_ext);
    bits(out, &format!("{tag}.work.field"), s.work.field);
    bits(out, &format!("{tag}.drift"), s.drift());
    let _ = writeln!(out, "{tag}.physics_digest={:016x}", holon_render::checkpoint::physics_digest(s));
    let _ = writeln!(out, "{tag}.steps={}", s.steps);
    for &f in FLOORS.iter() {
        match s.derive_pair_cutoff(f) {
            Some((r_in, r_cut)) => {
                let _ = writeln!(out, "{tag}.cutoff[{f:e}]={:016x},{:016x}", r_in.to_bits(), r_cut.to_bits());
            }
            None => {
                let _ = writeln!(out, "{tag}.cutoff[{f:e}]=NONE");
            }
        }
    }
}

/// The far sector's closed-form radii on the power fixtures.
pub fn far_reading(out: &mut String) {
    for &p in POWERS.iter() {
        let far = FarSector::build(&[Some(power(p, 20.0))], 20.0, 1.0e-9, Dims::Two).expect("the power fixture builds");
        let m = far.model(0).expect("slot 0 has a model");
        for &b in BUDGETS.iter() {
            bits(out, &format!("far[p={p}].radius[{b:e}]"), m.radius_for_budget(b));
        }
        bits(out, &format!("far[p={p}].r_f"), far.r_f());
    }
}

/// THE WHOLE RECEIPT.
pub fn receipt() -> String {
    let mut out = String::new();
    let mut w = four_waters(Boundary::Walls);
    w.set_field(true, None).expect("walls admit the field");
    run(&mut w, WATER_STEPS);
    scene_reading(&mut out, "water4", &w);
    let mut q = quartet::quartet(false);
    run(&mut q, QUARTET_STEPS);
    scene_reading(&mut out, "quartet", &q);
    far_reading(&mut out);
    out
}

pub const RECEIPT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/channel_ledger.receipt");
