/-
CIRISHolon.SectionHolonomy — the gauge invariant SELECTOR-MAP found, banked.

WHAT THIS IS.  On the model family the selector campaigns run at (`n` fibers of
two states, a closed dynamics `T(i,b) = (m i, b + c i)` with `m` the macro map
and `c : Fin n → ZMod 2` the fiber-internal cochain), the question "does the
macro law lift into the micro world" has an exact answer: a **section** — one
micro state per fiber, closed under `T` — exists precisely when a **Z₂
holonomy** vanishes on every closed loop of `m`.  The holonomy is the object
`SELECTOR_MAP.md` recommended banking regardless of which selector wins: it is
what BOTH surviving candidates turn out to be measuring, it labels the gauge
orbits together with the macro cycle type, and it is the conjunct
`SELECTOR3_PREREG.md` stakes alongside fixed-point-freeness.

Three things are proved, and the split between them is the honest part:

* `hol_eq_zero_of_hasSection` — **necessity, in full generality** and for every
  `n`: if a section exists then every closed loop's holonomy is zero.  A
  section transports as `x (m^[k] i) = x i + hol m c i k`, so a loop that
  returns forces the holonomy to cancel.  No finiteness, no decidability.
* `hol_gauge` and `loopFree_gauge` — **the gauge statement, in full
  generality**: shifting `c` by the coboundary of any `σ` shifts the holonomy
  by `σ i + σ (m^[k] i)`, which is ZERO on a closed loop.  So the holonomy is
  a genuine invariant of the conjugation orbit and never a class marginal
  (the misfit `M-GAUGE-LAUNDER` names exactly this trap).
* `hasSection_iff_loopFree_three`, `hasSection_iff_loopFree_four` — **the
  converse, by exhaustion at n = 3 and n = 4**.  Sufficiency needs a choice of
  orbit representative, and rather than mechanize that choice this file settles
  it by `decide` at the two sizes the instruments actually used.  THE GENERAL
  CONVERSE IS NOT PROVED HERE and is not claimed; `SELECTOR3_PREREG.md`'s
  n = 5 run is measured, not machine-checked.

SCOPE, stated.  `Fin n` fibers of size exactly two; `ZMod 2` cochains; `m` an
arbitrary self-map, bijectivity assumed only where the finite instances quantify
over it.  This is a statement about the model family, NOT about physics, and it
selects nothing on its own — it supplies the invariant the selection criteria
are written in.  The campaign readings live in
`conformance/omega/SELECTOR_MAP.md` and `conformance/omega/SELECTOR3_PREREG.md`.

Convergent art, credited: the obstruction is a first cohomology class of the
cyclic group generated by `m` acting on `ZMod 2` — standard group cohomology,
and the "section exists iff the class vanishes" shape is the ordinary splitting
criterion.  The programme's own maintained-holonomy campaign found the same
shape on Wilson-loop transport; Break.lean's act-relative identity is what makes
the section's generated knob matter at all.
-/
import Mathlib.Tactic

namespace CIRISHolon.SectionHolonomy

variable {n : ℕ}

/-! ### Two facts about `ZMod 2`, settled by exhaustion -/

private theorem add_self (a : ZMod 2) : a + a = 0 := by revert a; decide

private theorem shuffle (p q r s t : ZMod 2) :
    p + q + r + (s + r + t) = p + s + q + t := by revert p q r s t; decide

private theorem shuffle' (a b u v : ZMod 2) :
    a + b + v = a + u + (b + u + v) := by revert a b u v; decide

/-! ### The holonomy -/

/-- The Z₂ holonomy of the cochain `c` along `k` steps of `m` starting at `i`:
    the sum of `c` over the orbit segment.  On a closed loop this is the
    obstruction; on an open segment it is the transport. -/
def hol (m : Fin n → Fin n) (c : Fin n → ZMod 2) (i : Fin n) (k : ℕ) : ZMod 2 :=
  ∑ j ∈ Finset.range k, c (m^[j] i)

@[simp] theorem hol_zero (m : Fin n → Fin n) (c : Fin n → ZMod 2) (i : Fin n) :
    hol m c i 0 = 0 := rfl

theorem hol_succ (m : Fin n → Fin n) (c : Fin n → ZMod 2) (i : Fin n) (k : ℕ) :
    hol m c i (k + 1) = hol m c i k + c (m^[k] i) :=
  Finset.sum_range_succ _ _

theorem hol_one (m : Fin n → Fin n) (c : Fin n → ZMod 2) (i : Fin n) :
    hol m c i 1 = c i := by
  rw [hol_succ, hol_zero, zero_add, Function.iterate_zero_apply]

/-! ### Sections -/

/-- `x` is a SECTION of the cochain: a choice of one micro state per fiber
    (`x i` is the within-fiber index) that the dynamics carries to itself. -/
def IsSection (m : Fin n → Fin n) (c x : Fin n → ZMod 2) : Prop :=
  ∀ i, x (m i) = x i + c i

/-- The macro law LIFTS: some section exists.  This is the subsystem whose
    generated knob is the only non-degenerate act vocabulary a world can build
    from the inside (SELECTOR-3's `A(T)`). -/
def HasSection (m : Fin n → Fin n) (c : Fin n → ZMod 2) : Prop :=
  ∃ x, IsSection m c x

instance (m : Fin n → Fin n) (c x : Fin n → ZMod 2) : Decidable (IsSection m c x) :=
  inferInstanceAs (Decidable (∀ i, x (m i) = x i + c i))

instance (m : Fin n → Fin n) (c : Fin n → ZMod 2) : Decidable (HasSection m c) :=
  inferInstanceAs (Decidable (∃ x, IsSection m c x))

/-- Every closed loop of `m` has vanishing holonomy. -/
def LoopFree (m : Fin n → Fin n) (c : Fin n → ZMod 2) : Prop :=
  ∀ i k, m^[k] i = i → hol m c i k = 0

/-- **Transport.**  A section moves along the orbit by exactly the holonomy. -/
theorem section_transport {m : Fin n → Fin n} {c x : Fin n → ZMod 2}
    (h : IsSection m c x) (k : ℕ) (i : Fin n) :
    x (m^[k] i) = x i + hol m c i k := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [Function.iterate_succ_apply', h (m^[k] i), ih, hol_succ, add_assoc]

/-- **Necessity, in full generality.**  If the macro law lifts, every closed
    loop's holonomy vanishes: the section returns to where it started, so the
    accumulated cochain must cancel. -/
theorem hol_eq_zero_of_hasSection {m : Fin n → Fin n} {c : Fin n → ZMod 2}
    (h : HasSection m c) : LoopFree m c := by
  obtain ⟨x, hx⟩ := h
  intro i k hk
  have := section_transport hx k i
  rw [hk] at this
  exact (self_eq_add_right.mp this)

/-- The fixed-point corollary, which is the sector SELECTOR-3's mechanism turns
    on: wherever the macro law stands still, the cochain must be zero. -/
theorem eq_zero_of_fixed {m : Fin n → Fin n} {c : Fin n → ZMod 2}
    (h : LoopFree m c) {i : Fin n} (hi : m i = i) : c i = 0 := by
  have h1 : m^[1] i = i := by rwa [Function.iterate_one]
  have := h i 1 h1
  rwa [hol_one] at this

/-- The stasis corner: the zero cochain always lifts (take the zero section).
    Structure is not what the dead world lacks — SELECTOR-3's plant (i) is that
    its generated ACTS collapse, not its subsystems. -/
theorem hasSection_zero (m : Fin n → Fin n) : HasSection m (fun _ => 0) :=
  ⟨fun _ => 0, fun _ => by simp⟩

/-! ### The gauge statement -/

/-- A GAUGE transformation of the cochain: `c` shifted by the coboundary of
    `σ`.  Conjugating the dynamics by a fiber-wise flip does exactly this. -/
def gauge (m : Fin n → Fin n) (c σ : Fin n → ZMod 2) : Fin n → ZMod 2 :=
  fun i => c i + σ i + σ (m i)

/-- **The transport shifts by a boundary term.**  Telescoping: only the two
    ends of the segment survive. -/
theorem hol_gauge (m : Fin n → Fin n) (c σ : Fin n → ZMod 2) (i : Fin n) (k : ℕ) :
    hol m (gauge m c σ) i k = hol m c i k + σ i + σ (m^[k] i) := by
  induction k with
  | zero => simp [add_self]
  | succ k ih =>
      rw [hol_succ, ih, hol_succ, Function.iterate_succ_apply']
      exact shuffle _ _ _ _ _

/-- **The holonomy is a gauge invariant.**  On a closed loop the two boundary
    terms are the same point and cancel, so `LoopFree` is a property of the
    conjugation orbit — never a class marginal (`M-GAUGE-LAUNDER`). -/
theorem loopFree_gauge (m : Fin n → Fin n) (c σ : Fin n → ZMod 2) :
    LoopFree m (gauge m c σ) ↔ LoopFree m c := by
  constructor <;> intro h i k hk <;> have := h i k hk
  · rwa [hol_gauge, hk, add_assoc, add_self, add_zero] at this
  · rw [hol_gauge, hk, add_assoc, add_self, add_zero, this]

/-- Sections transport to sections under a gauge transformation, exhibited: the
    gauge-shifted cochain lifts exactly when the original does. -/
theorem hasSection_gauge (m : Fin n → Fin n) (c σ : Fin n → ZMod 2)
    (h : HasSection m c) : HasSection m (gauge m c σ) := by
  obtain ⟨x, hx⟩ := h
  exact ⟨fun i => x i + σ i, fun i => by
    simp only [gauge, hx i]; exact shuffle' _ _ _ _⟩

/-! ### The converse, by exhaustion at the sizes the instruments used -/

/-- The bounded form of `LoopFree`, decidable.  The bound must be `n + 1`, not
    `n`: the return time of a point of `Fin n` under a bijection is at most `n`,
    and `k < n` would MISS the full-length cycle — at `n = 3` the bound `3` makes
    the biconditional below actually false, which `decide` reported. -/
def LoopFreeB (B : ℕ) (m : Fin n → Fin n) (c : Fin n → ZMod 2) : Prop :=
  ∀ i, ∀ k < B, m^[k] i = i → hol m c i k = 0

instance (B : ℕ) (m : Fin n → Fin n) (c : Fin n → ZMod 2) :
    Decidable (LoopFreeB B m c) :=
  inferInstanceAs (Decidable (∀ i, ∀ k < B, m^[k] i = i → hol m c i k = 0))

theorem loopFreeB_of_loopFree {B : ℕ} {m : Fin n → Fin n} {c : Fin n → ZMod 2}
    (h : LoopFree m c) : LoopFreeB B m c := fun i k _ hk => h i k hk

set_option maxRecDepth 100000 in
/-- **n = 3, exhaustive.**  Over all 27 self-maps of `Fin 3`, every bijection
    and every one of the 8 cochains: the macro law lifts iff the holonomy
    vanishes on every loop of length at most 3. -/
theorem hasSection_iff_loopFree_three :
    ∀ m : Fin 3 → Fin 3, Function.Bijective m → ∀ c : Fin 3 → ZMod 2,
      (HasSection m c ↔ LoopFreeB 4 m c) := by decide

set_option maxRecDepth 1000000 in
/-- **n = 4, exhaustive** — the first size the SELECTOR-3 forward test used. -/
theorem hasSection_iff_loopFree_four :
    ∀ m : Fin 4 → Fin 4, Function.Bijective m → ∀ c : Fin 4 → ZMod 2,
      (HasSection m c ↔ LoopFreeB 5 m c) := by decide

/-- The full circle at n = 3, composing the general necessity with the decided
    converse: lifting, loop-freeness, and its bounded form are one condition. -/
theorem section_iff_loopFree_three (m : Fin 3 → Fin 3) (hm : Function.Bijective m)
    (c : Fin 3 → ZMod 2) :
    HasSection m c ↔ LoopFree m c :=
  ⟨hol_eq_zero_of_hasSection,
   fun h => (hasSection_iff_loopFree_three m hm c).mpr (loopFreeB_of_loopFree h)⟩

/-- The same circle at n = 4. -/
theorem section_iff_loopFree_four (m : Fin 4 → Fin 4) (hm : Function.Bijective m)
    (c : Fin 4 → ZMod 2) :
    HasSection m c ↔ LoopFree m c :=
  ⟨hol_eq_zero_of_hasSection,
   fun h => (hasSection_iff_loopFree_four m hm c).mpr (loopFreeB_of_loopFree h)⟩

end CIRISHolon.SectionHolonomy
