#!/usr/bin/env python3
"""selector6.py — the SELECTOR-6 runner.

WHAT IS INHERITED AND WHAT IS NEW, stated exactly.

INHERITED VERBATIM from the frozen criterion (s4core.py, generated by
make_s4core.py from selector4.py blob d33f0469):
    build_world, separates, knobs_partial_sections, acts_are_bijections,
    cycles_of, inv_perm, closed_at, gauge_invariant_view, refines, divisors
These ARE the criterion.  Not one line of them is touched.

NEW HERE — the aggregation layer the design declares, and nothing else:
    * the FULL dressed family F(G) = {GAUGE[g] . step^d}, replacing
      selector4's one-representative-per-class family (AMENDMENT A1 item 1);
    * the gauge-orbit decomposition that recovers the economy;
    * the per-group verdict SELECT(G), which selector4 had no need of because
      it reported per-(world, rung) selected sets rather than per-group booleans.

selector4's `run_rung` is a DRIVER, not the criterion: it loops, groups by the
single-step reading, and caches.  SELECTOR-6 writes its own driver because the
home loop is exactly where the aggregation lives (homes range over gauge-orbit
representatives, partners over all of F).  Every decision inside that driver is
still made by the inherited `separates`.

The one optimisation carried over from run_rung -- the divisor-pair cache used
when the view is gauge-invariant and the home's act vocabulary is empty -- is an
optimisation, not a criterion change, so it is VERIFIED rather than trusted:
CHEAP_AUDIT pairs per group are answered by BOTH routes and must agree.
"""
import json
import os
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import s4core as S4

# ---- declared budgets (SELECTOR6_DESIGN.md section 5.3)
BUDGET = S4.BUDGET                 # 2000 rho-nodes, inherited unchanged
GROUP_BFS_BUDGET = 300_000         # 10x the measured worst case (F_57: 30,408)
GROUP_WALL = 3600.0                # seconds
ORBIT_CHECK_S = 3                  # orbit reps re-checked per group
CHEAP_AUDIT = 12                   # pairs per group cross-checked cheap vs full

# ---- ruling 3 (proposed; NOT yet ruled by the lead as of design v2)
# A VOID at rung k removes rung k and every finer rung.  If the finest surviving
# rung is A2 or coarser the group VOIDs rather than scoring SELECT=False, so a
# budget exhaustion can never be recorded as a negative verdict.
MIN_DECIDED_RUNG = 3


class Refused(Exception):
    pass


def build_family(W):
    """F(G) = {GAUGE[g] . step^d : g in G, d | ord(step)}, deduplicated, with
    its gauge-orbit partition.  A function of (MUL, INV) with no choices."""
    n = W["n"]
    divs = S4.divisors(W["ordstep"])
    powers, x, dset = {}, W["idp"].copy(), set(divs)
    for d in range(1, max(divs) + 1):
        x = W["step"][x]
        if d in dset:
            powers[d] = x.astype(np.int32)
    index, members, perms = {}, [], []
    for d in divs:
        for g in range(n):
            p = W["GAUGE"][g][powers[d]].astype(np.int32)
            key = p.tobytes()
            if key not in index:
                index[key] = len(members)
                members.append((d, g))
                perms.append(p)
    MUL, INV = W["MUL"], W["INV"]
    orbit_of = [-1] * len(members)
    reps, sizes = [], []
    ar = np.arange(n)
    for i, (d, g) in enumerate(members):
        if orbit_of[i] >= 0:
            continue
        orb = set()
        for x_ in range(n):
            gg = int(MUL[MUL[x_, g], INV[x_]])
            orb.add(index[W["GAUGE"][gg][powers[d]].astype(np.int32).tobytes()])
        lab = len(reps)
        for j in orb:
            orbit_of[j] = lab
        reps.append(i)
        sizes.append(len(orb))
    return members, perms, orbit_of, reps, sizes, powers


def run_group(W, members, perms, orbit_of, reps, sizes, powers, homes=None,
              deadline=None):
    """Per-rung selected sets.  Returns dict rung -> (sel_count, void_count) plus
    diagnostics.  `homes` overrides the orbit representatives (used by the
    orbit-constancy check)."""
    N, idp = W["N"], W["idp"]
    # The equivariance lemma has three hypotheses (SELECTOR6_DESIGN.md section 2).
    # Two are per-group facts and are CHECKED here rather than assumed; the third
    # (the view is gauge-invariant) is checked per rung below.  If either fails,
    # the gauge-orbit economy is not valid for this group and it must VOID rather
    # than be scored on an unproved decomposition.
    for g in W["GAUGE"]:
        if not np.array_equal(g[W["step"]], W["step"][g]):
            raise Refused("gauge action does not commute with the step")
        if len(set(g.tolist())) != N:
            raise Refused("gauge action not bijective")
    F = len(members)
    is_home = np.zeros(F, bool)
    for i in (reps if homes is None else homes):
        is_home[i] = True
    out = {}
    bfs_calls = 0
    audits = []
    for k in range(5):
        view = W["V"][k]
        if int(view.max()) == 0:
            out[k] = dict(sel=0, voids=0, mode="analytic-A0", homes=len(reps))
            continue
        ginv = S4.gauge_invariant_view(view, W["GAUGE"])
        if not ginv:
            out[k] = dict(sel=None, voids=1, mode="VOID-view-not-gauge-invariant")
            continue
        # canonical ids for view o step^j, for the empty-vocabulary fast path
        L = W["ordstep"]
        idmap, seqids, x = {}, [], idp.copy()
        for _ in range(L):
            seqids.append(idmap.setdefault(view[x].tobytes(), len(idmap)))
            x = W["step"][x]
        dcache = {}

        groups = {}
        for i in range(F):
            groups.setdefault(view[perms[i]].tobytes(), []).append(i)

        sel_count, voids = 0, 0
        for mem in groups.values():
            if len(mem) == 1:
                for i in mem:
                    if is_home[i]:
                        sel_count += sizes[orbit_of[i]]
                continue
            for i in mem:
                if not is_home[i]:
                    continue
                if deadline and time.time() > deadline:
                    raise Refused("GROUP_WALL")
                cyc, cid = S4.knobs_partial_sections(perms[i], view, N)
                if not S4.acts_are_bijections(cyc, perms[i]):
                    raise Refused("act carrier not dynamics-invariant")
                act = (cyc, cid, S4.inv_perm(perms[i], N))
                alone, void_here = True, False
                for j in mem:
                    if i == j:
                        continue
                    if ginv and not cyc:
                        key = (members[i][0], members[j][0])
                        if key not in dcache:
                            d1, d2 = key
                            dcache[key] = any(
                                seqids[(d1 * kk) % L] != seqids[(d2 * kk) % L]
                                for kk in range(1, L + 1))
                        s = dcache[key]
                        if len(audits) < CHEAP_AUDIT:
                            full = S4.separates(act, perms[i], perms[j], view, N, idp)
                            if full is not None:
                                audits.append((s, full))
                    else:
                        bfs_calls += 1
                        if bfs_calls > GROUP_BFS_BUDGET:
                            raise Refused("GROUP_BFS_BUDGET")
                        s = S4.separates(act, perms[i], perms[j], view, N, idp)
                    if s is None:
                        void_here = True
                        break
                    if not s:
                        alone = False
                        break
                if void_here:
                    voids += 1
                elif alone:
                    sel_count += sizes[orbit_of[i]]
        out[k] = dict(sel=sel_count, voids=voids, mode="measured",
                      homes=int(is_home.sum()))
    return out, bfs_calls, audits


def verdict(per_rung, Fsize):
    """SELECT(G) at the finest decided rung, with ruling 3's refusal."""
    kstar = None
    for k in range(4, -1, -1):
        r = per_rung.get(k)
        if r is None or r["sel"] is None:
            continue
        if r["voids"] == 0:
            kstar = k
            break
    if kstar is None or kstar < MIN_DECIDED_RUNG:
        return None, kstar, None
    sel = per_rung[kstar]["sel"]
    return (0 < sel < Fsize), kstar, sel
