#!/usr/bin/env python3
"""SELECTOR-3 — the observer bootstrap, forward-staked.

Implements conformance/omega/SELECTOR3_PREREG.md exactly.  Exact, integer /
Fraction arithmetic throughout; no sampling, no word-length cut, no fitting.

THE STAKED MECHANISM, frozen before this instrument existed:

    |Ident_{A(T)}(T)| = 1  iff  the macro map is FIXED-POINT-FREE
                                and the Z2 holonomy vanishes on every cycle.

THE MODEL FAMILY.  n fibers of size 2 (states 2i, 2i+1 in fiber i), the view
being the fiber map.  A closed dynamics is T(i,b) = (m(i), b XOR c_i) with
m in S_n and c in {0,1}^n — that is exactly the set of bijections carrying
fibers onto fibers, and there are n!*2^n of them.  n = 3 is the census that
GENERATED the hypothesis (derivation, not evidence); n = 4 and n = 5 are the
forward tests.

THE ACT VOCABULARY.  A(T) is generated by T's own SECTION subsystems: a
T-invariant transversal X (one state per fiber, closed under T) yields the
knob a_X(s) = T(s) for s in X, s otherwise.  Sections are definable from
(view, dyn) alone.  The prereg's interpretive fence is committed: a world's
internal observers may implement acts they cannot name with their own meter.
The view-aligned vocabulary is NOT used as the candidate's vocabulary — by
Break.lean's `vcov_preservesGauge_of_closed` (T3) it is provably powerless —
but it IS re-run at every n as plant (ii), a live theorem control.

SEPARATION is decided exactly.  For a home T and a candidate T', BFS the
reachable set of state PAIRS under letters {step, knobs}, step advancing T on
the left and T' on the right, knobs applied to both.  Separated iff some
reachable pair is split by the view.  The BFS closes the relation, so this
quantifies over ALL experiment words with no depth bound (M-FINAL-VIEW-
COLLISIONS).  Candidates with a different macro map are separated at depth 1
by an EXHIBITED witness (the word [step] from any state of a fiber where the
macro maps differ) rather than by BFS; at n = 3 and n = 4 the full exhaustive
pair-BFS is run over every candidate anyway and the two agree — the witness
route is checked, not assumed.

EXIT CONTRACT.  0 = every staked gate passed and both plants fired.
2 = the instrument is valid but a staked gate KILLED (branch (b)) — a real
result, not a broken run.  1 = the instrument itself is invalid: an internal
inconsistency, a VOID, or a plant that failed to fire.

Credits (house rule): Wheeler (law without law — the participatory loop as a
fixed-point condition); Deutsch & Marletto (constructor theory — the
possible/impossible dichotomy is the act vocabulary); Rovelli (relational QM);
Break.lean's gauge_safety/T3 for the machine-checked negative half;
Kolchinsky & Wolpert and Montevil & Mossio in SELECTOR-1's shared lineage.
"""
import sys
from fractions import Fraction as F
from itertools import permutations, product

LOG = open(__file__.replace(".py", ".log"), "w")
VOID = []


def log(s=""):
    print(s)
    LOG.write(s + "\n")
    LOG.flush()


def void(cond, msg):
    if not cond:
        VOID.append(msg)
    return cond


# =========================================================== the model family
def family(n):
    """All closed dynamics on n fibers of size 2, as permutation tuples of the
    2n states, tagged with their (m, c) coordinates."""
    out = []
    for m in permutations(range(n)):
        for c in product((0, 1), repeat=n):
            T = tuple(2 * m[s >> 1] + ((s & 1) ^ c[s >> 1]) for s in range(2 * n))
            out.append((T, m, c))
    return out


def cycles(m):
    seen, cyc = set(), []
    for i in range(len(m)):
        if i in seen:
            continue
        cy, j = [], i
        while j not in seen:
            seen.add(j)
            cy.append(j)
            j = m[j]
        cyc.append(cy)
    return cyc


def holonomy(m, c):
    """The conjugation-invariant label: the multiset of (cycle length, Z2
    holonomy of c around that cycle).  Conjugation shifts c by a coboundary,
    which leaves every cycle sum fixed — so this is a gauge invariant, never a
    class marginal (M-GAUGE-LAUNDER, M-LOOP-BLIND)."""
    return tuple(sorted((len(cy), sum(c[i] for i in cy) % 2) for cy in cycles(m)))


def fixed_point_free(m):
    return all(m[i] != i for i in range(len(m)))


def mechanism_predicts(m, c):
    """The STAKED mechanism, evaluated on (m, c) alone — no reference to any
    measured identity set."""
    return fixed_point_free(m) and all(h == 0 for _, h in holonomy(m, c))


def sections(T, n):
    """T-invariant transversals: one state per fiber, closed under T."""
    out = []
    for x in product((0, 1), repeat=n):
        X = frozenset(2 * i + x[i] for i in range(n))
        if {T[s] for s in X} == set(X):
            out.append(X)
    return out


def knobs_section(T, n):
    """A(T): the acts T's own sections implement.  Deduplicated — a repeated
    letter adds no words."""
    return sorted({tuple(T[s] if s in X else s for s in range(2 * n))
                   for X in sections(T, n)})


def knobs_view_aligned(T, n):
    """The provably powerless vocabulary (plant ii): T restricted to unions of
    view blocks.  Every such act is view-covariant, hence gauge-safe on a
    closed holon by Break.lean T3."""
    return sorted({tuple(T[s] if B[s >> 1] else s for s in range(2 * n))
                   for B in product((0, 1), repeat=n)})


# ==================================================== exact separation by BFS
def separates(knobs, T, Tp, n):
    """Exact over ALL experiment words: BFS the reachable state-pair relation."""
    N = 2 * n
    seen = bytearray(N * N)
    stack = []
    for s in range(N):
        seen[s * N + s] = 1
        stack.append((s, s))
    while stack:
        x, y = stack.pop()
        if (x >> 1) != (y >> 1):
            return True
        nx, ny = T[x], Tp[y]
        if not seen[nx * N + ny]:
            seen[nx * N + ny] = 1
            stack.append((nx, ny))
        for a in knobs:
            nx, ny = a[x], a[y]
            if not seen[nx * N + ny]:
                seen[nx * N + ny] = 1
                stack.append((nx, ny))
    return False


def cross_macro_witness(m, mp):
    """The depth-1 separation witness for candidates with different macro maps:
    the word [step] from any state of a fiber where the macro maps differ.
    Exhibited, not assumed."""
    for i in range(len(m)):
        if m[i] != mp[i]:
            return i
    return None


def ident_set(T, m, c, knobs, fam, n, exhaustive, by_m=None):
    """|Ident_{knobs}(T)| over the whole candidate family.

    exhaustive=True runs the pair-BFS against EVERY candidate (gate B0's
    literal reading).  exhaustive=False uses the exhibited depth-1 witness for
    different-macro candidates and BFS for the rest; at n = 3 and n = 4 both
    are run and required to agree."""
    cand = fam if exhaustive else by_m[m]
    return [(Tp, mp, cp) for (Tp, mp, cp) in cand
            if not separates(knobs, T, Tp, n)]


# ============================================== the view lattice (gate N2/S6)
def view_labels(k):
    """Every view on k states, as a label array — the restricted-growth strings,
    which enumerate set partitions exactly once each (Bell(k) of them)."""
    out, lab = [], [0] * k

    def rec(i, mx):
        if i == k:
            out.append(lab[:])
            return
        for v in range(mx + 2):
            lab[i] = v
            rec(i + 1, max(mx, v))
    rec(1, 0)
    return out


def rent_num(T, lab, nb, N):
    """The Ω rent at one view, as an INTEGER numerator over N: the mass the best
    deterministic coarse map fails to carry, times N.  Integer arithmetic — the
    sorted rent multiset is the histogram of these, and there are at most N + 1
    possible values, which is what makes N3 affordable at n = 5."""
    cnt = {}
    for s in range(N):
        k = lab[s] * nb + lab[T[s]]
        cnt[k] = cnt.get(k, 0) + 1
    best = [0] * nb
    for k, v in cnt.items():
        a = k // nb
        if v > best[a]:
            best[a] = v
    return N - sum(best)


def viewindexed_separates(members, repB, labs, vnb, N, prefix=3000):
    """Is orbit A's rep separated from orbit B's rep by the VIEW-INDEXED rent
    profile, up to gauge?  Exact: quantify over every member of A's orbit (the
    conjugates) and ask whether any has the identical view-by-view profile as
    B.  Fast path: profiles that already differ on a prefix of the lattice
    differ, full stop; only a conjugate agreeing on the whole prefix is checked
    against the whole lattice."""
    prof_pref = [rent_num(repB, labs[v], vnb[v], N) for v in range(min(prefix, len(labs)))]
    survivors = []
    for TA in members:
        if all(rent_num(TA, labs[v], vnb[v], N) == prof_pref[v]
               for v in range(len(prof_pref))):
            survivors.append(TA)
    if not survivors:
        return True
    profB = [rent_num(repB, labs[v], vnb[v], N) for v in range(len(labs))]
    for TA in survivors:
        if all(rent_num(TA, labs[v], vnb[v], N) == profB[v] for v in range(len(labs))):
            return False
    return True


def n_closed_views(T, labs, k):
    """The count of views at which T closes: partitions whose blocks T permutes
    (rent exactly zero).  This is S6's quantity — accidental closure."""
    tot = 0
    for lab in labs:
        img = {}
        ok = True
        for s in range(k):
            a, b = lab[s], lab[T[s]]
            if img.setdefault(a, b) != b:
                ok = False
                break
        if ok:
            tot += 1
    return tot


def perm_order(T):
    x, k = tuple(range(len(T))), 0
    while True:
        x = tuple(T[i] for i in x)
        k += 1
        if x == tuple(range(len(T))):
            return k


# =========================================================== the derived law
def mechanism_fraction_closed_form(n):
    """A CONSEQUENCE of the staked mechanism, not independent evidence: the
    selected count is sum over derangements m of 2^(n - #cycles(m)), so the
    fraction is [x^n] (1-x)^(-1/2) e^(-x/2).  Reported because a fraction that
    falls on three points is weaker than a fraction with a law that falls to
    zero — and the law is checked against the enumeration at every n."""
    N = n + 1
    a = [F(0)] * N            # (1-x)^(-1/2)
    a[0] = F(1)
    for k in range(1, N):
        a[k] = a[k - 1] * F(2 * k - 1, 2 * k)
    b = [F(0)] * N            # e^(-x/2)
    b[0] = F(1)
    for k in range(1, N):
        b[k] = b[k - 1] * F(-1, 2 * k)
    return sum(a[k] * b[n - k] for k in range(N))


# ==================================================================== the run
def run_n(n, exhaustive, do_views):
    import math
    fam = family(n)
    W = len(fam)
    by_m = {}
    for x in fam:
        by_m.setdefault(x[1], []).append(x)
    # The cross-macro separation witness depends only on the pair of macro maps,
    # so it is exhibited once per macro-map pair — exhaustive over every pair.
    for m1 in by_m:
        for m2 in by_m:
            if m1 != m2:
                void(cross_macro_witness(m1, m2) is not None,
                     f"n={n}: cross-macro pair with no depth-1 witness")
    void(W == math.factorial(n) * 2 ** n, f"n={n}: family size wrong")
    for (T, m, c) in fam:
        void(sorted(T) == list(range(2 * n)), f"n={n}: a dynamics is not bijective")

    # --- orbits: brute conjugation where affordable, else the invariant label
    label = {}
    for (T, m, c) in fam:
        label[T] = (tuple(sorted(len(cy) for cy in cycles(m))), holonomy(m, c))
    lab_classes = len({v for v in label.values()})
    brute = None
    if n <= 4:
        inv = {}
        for (T, m, c) in fam:
            g = [0] * (2 * n)
            for s in range(2 * n):
                g[T[s]] = s
            inv[T] = tuple(g)
        orb_of, orbs = {}, []
        for (T, m, c) in fam:
            if T in orb_of:
                continue
            o = frozenset(tuple(g[T[inv[g][s]]] for s in range(2 * n))
                          for (g, _, _) in fam)
            orbs.append(o)
            for q in o:
                orb_of[q] = len(orbs) - 1
        brute = len(orbs)
        void(sum(len(o) for o in orbs) == W, f"n={n}: orbits do not partition")
        void(brute == lab_classes,
             f"n={n}: the (cycle-type, holonomy) label is not the orbit label "
             f"({lab_classes} vs {brute})")
        for o in orbs:
            void(len({label[q] for q in o}) == 1,
                 f"n={n}: the holonomy label is not conjugation-invariant")

    # --- identity sets, both vocabularies
    boot, va_sizes, sec_sizes = [], set(), {}
    ex_agree = True
    for (T, m, c) in fam:
        ks = knobs_section(T, n)
        idset = ident_set(T, m, c, ks, fam, n, False, by_m)
        if exhaustive:
            full = ident_set(T, m, c, ks, fam, n, True, by_m)
            if len(full) != len(idset):
                ex_agree = False
        sec_sizes[T] = len(idset)
        if len(idset) == 1:
            void(idset[0][0] == T, f"n={n}: a singleton identity set is not T")
            boot.append((T, m, c))
        kv = knobs_view_aligned(T, n)
        va_sizes.add(len(ident_set(T, m, c, kv, fam, n, False, by_m)))
    if exhaustive:
        void(ex_agree, f"n={n}: exhaustive BFS disagrees with the witness route")

    # --- orbit-invariance of the measured identity set (licenses the label)
    by_label = {}
    for (T, m, c) in fam:
        by_label.setdefault(label[T], set()).add(sec_sizes[T])
    void(all(len(v) == 1 for v in by_label.values()),
         f"n={n}: |Ident| is not orbit-invariant — the criterion is not Ω-internal")

    # --- M1: the mechanism, world by world
    dev = []
    for (T, m, c) in fam:
        if (sec_sizes[T] == 1) != mechanism_predicts(m, c):
            dev.append((m, c, sec_sizes[T]))

    # --- plants
    ident_world = tuple(range(2 * n))
    idT = next(x for x in fam if x[0] == ident_world)
    p1_acts = set(knobs_section(idT[0], n))
    p1 = (p1_acts == {ident_world}) and sec_sizes[ident_world] != 1
    p2 = (va_sizes == {2 ** n})

    # --- N2 / S6
    s6, n3 = None, None
    if do_views:
        labs = view_labels(2 * n)
        reps = {}
        for (T, m, c) in fam:
            reps.setdefault(label[T], (T, m, c))
        N = 2 * n
        # per-view precomputation shared by every orbit representative
        vnb = [max(lab) + 1 for lab in labs]
        vtype = []
        for lab in labs:
            sz = [0] * (max(lab) + 1)
            for v in lab:
                sz[v] += 1
            vtype.append(tuple(sorted(sz)))
        rep_lbls = list(reps.keys())
        hist_plain = {lb: {} for lb in rep_lbls}
        hist_typed = {lb: {} for lb in rep_lbls}
        ncl = {lb: 0 for lb in rep_lbls}
        for vi in range(len(labs)):
            lab, nb, ty = labs[vi], vnb[vi], vtype[vi]
            for lb in rep_lbls:
                r = rent_num(reps[lb][0], lab, nb, N)
                hist_plain[lb][r] = hist_plain[lb].get(r, 0) + 1
                key = (ty, r)
                hist_typed[lb][key] = hist_typed[lb].get(key, 0) + 1
                if r == 0:
                    ncl[lb] += 1
        void(all(ncl[label[T]] == n_closed_views(T, labs, N)
                 for (T, m, c) in fam[:min(len(fam), 40)]),
             f"n={n}: the fused view sweep disagrees with the direct closed count")
        # N3: sorted-rent-multiset collisions between DISTINCT orbits.  The
        # multiset is exactly the histogram, so equality of histograms is the
        # collision test, with no floating point anywhere.
        seen_h, coll = {}, []
        for lb in rep_lbls:
            key = tuple(sorted(hist_plain[lb].items()))
            seen_h.setdefault(key, []).append(lb)
        for key, lbs in seen_h.items():
            if len(lbs) > 1:
                for a in range(len(lbs)):
                    for b in range(a + 1, len(lbs)):
                        la, lb2 = lbs[a], lbs[b]
                        pa, pb = reps[la], reps[lb2]
                        # macro period of each colliding world
                        per_a = perm_order(tuple(pa[1]))
                        per_b = perm_order(tuple(pb[1]))
                        typed_sep = (tuple(sorted(hist_typed[la].items()))
                                     != tuple(sorted(hist_typed[lb2].items())))
                        # the recoverability half, done exactly at EVERY n: the
                        # FULL view-indexed profile up to gauge, quantified over
                        # every conjugate.  The prefix fast path is what makes
                        # the 115975-view lattice affordable; it can only prove
                        # separation, never miss one.
                        mem = [x[0] for x in fam if label[x[0]] == la]
                        vsep = viewindexed_separates(mem, pb[0], labs, vnb, N)
                        coll.append(dict(a=la, b=lb2, per=(per_a, per_b),
                                         equal_period=(per_a == per_b),
                                         typed_separates=typed_sep,
                                         view_separates=vsep))
        n3 = dict(n_orbits=len(rep_lbls), n_spectra=len(seen_h), collisions=coll,
                  all_differ=all(not c["equal_period"] for c in coll),
                  all_recoverable=all(c["view_separates"] for c in coll
                                      if c["view_separates"] is not None),
                  recoverable_computed=all(c["view_separates"] is not None
                                           for c in coll))
        lo = min(ncl.values())
        argmin_lbls = [lb for lb, v in ncl.items() if v == lo]
        argmin = [x for x in fam if label[x[0]] in argmin_lbls]
        maxord = max(perm_order(x[0]) for x in fam)
        # Two candidate readings of "the maximal scrambler", which coincide at
        # small n and must be separated: MAXIMAL ORDER, and SINGLE-CYCLE (the
        # micro permutation is transitive on all 2n states).
        onecyc = {x[0] for x in fam if perm_order(x[0]) == 2 * n}
        maxo = {x[0] for x in fam if perm_order(x[0]) == maxord}
        s6 = dict(views=len(labs), lo=lo, hi=max(ncl.values()),
                  argmin_orders=sorted({perm_order(x[0]) for x in argmin}),
                  maxord=maxord, n_argmin=len(argmin),
                  scrambler=(sorted({perm_order(x[0]) for x in argmin}) == [maxord]),
                  is_onecycle=({x[0] for x in argmin} == onecyc),
                  readings_coincide=(onecyc == maxo),
                  identity_is_argmax=(ncl[label[ident_world]] == max(ncl.values())))
        if n <= 4:
            for (T, m, c) in fam:
                void(n_closed_views(T, labs, N) == ncl[label[T]],
                     f"n={n}: closed-view count is not orbit-invariant")

    return dict(n=n, worlds=W, orbits=(brute if brute else lab_classes),
                orbits_by_label=lab_classes, brute=brute,
                boot=len(boot), frac=F(len(boot), W), dev=dev,
                sec_sizes=sorted(set(sec_sizes.values())),
                va_sizes=sorted(va_sizes), p1=p1, p2=p2, s6=s6, n3=n3,
                closed_form=mechanism_fraction_closed_form(n))


def main():
    log("=" * 78)
    log("SELECTOR-3 — the observer bootstrap, forward-staked")
    log("prereg: conformance/omega/SELECTOR3_PREREG.md (frozen before this file)")
    log("=" * 78)
    log()
    log("A.  THE STAKED MECHANISM (quoted from the freeze)")
    log("-" * 78)
    log("    |Ident_A(T)(T)| = 1  iff  the macro map is FIXED-POINT-FREE")
    log("                              and the Z2 holonomy vanishes on every cycle.")
    log()

    R = {}
    for n, exhaustive, views in ((3, True, True), (4, True, True), (5, False, True)):
        log(f"B.  n = {n}  ({'DERIVATION — generated the hypothesis, not evidence' if n == 3 else 'FORWARD TEST'})")
        log("-" * 78)
        r = run_n(n, exhaustive, views)
        R[n] = r
        log(f"    worlds (closed dynamics)      : {r['worlds']}")
        log(f"    gauge orbits                  : {r['orbits']}"
            f"{'  (brute conjugation, = the label)' if r['brute'] else '  (holonomy label; brute verified at n<=4)'}")
        log(f"    |Ident| values observed       : section acts {r['sec_sizes']}, "
            f"view-aligned acts {r['va_sizes']}")
        log(f"    bootstrap passes              : {r['boot']}/{r['worlds']} "
            f"= {r['frac']} = {float(r['frac']):.6f}")
        log(f"    mechanism deviations          : {len(r['dev'])}")
        if r["dev"]:
            for (m, c, sz) in r["dev"][:8]:
                log(f"        m={m} c={c} |Ident|={sz} "
                    f"predicted={mechanism_predicts(m, c)}")
        log(f"    separation route              : "
            f"{'FULL exhaustive pair-BFS over every candidate, agreeing with the witness route' if exhaustive else 'exhibited depth-1 witness for cross-macro pairs + exhaustive pair-BFS within the macro class'}")
        log(f"    closed form [x^n](1-x)^-1/2 e^-x/2 : {r['closed_form']} "
            f"-> {'MATCHES' if r['closed_form'] == r['frac'] else 'DIFFERS'} the measured fraction")
        if r["s6"]:
            s = r["s6"]
            log(f"    S6: {s['views']} views; closed-view count {s['lo']}..{s['hi']}; "
                f"argmin on {s['n_argmin']} worlds of order {s['argmin_orders']} "
                f"(max order in family = {s['maxord']})")
        log()

    log("C.  VERDICTS")
    log("-" * 78)
    b0 = (not VOID)
    log(f"  B0  : {'PASS' if b0 else 'VOID'} — all dynamics bijective; identity sets "
        f"by exhaustive pair-BFS (full at n=3,4; witness+BFS at n=5, the witness "
        f"exhibited per pair); |Ident| verified orbit-invariant at every n")
    dev_tot = sum(len(R[n]['dev']) for n in (4, 5))
    m1 = (dev_tot == 0)
    log(f"  M1  : mechanism deviations at n=4: {len(R[4]['dev'])}, n=5: "
        f"{len(R[5]['dev'])} -> {'branch (a)' if m1 else 'branch (b)'}")
    if m1:
        log(f"        the biconditional holds across ALL cycle types at n=4 AND n=5:")
        log(f"        rule-6 support for a selection principle — staked before the "
            f"instrument existed.")
    else:
        types = sorted({tuple(sorted(len(cy) for cy in cycles(m)))
                        for n in (4, 5) for (m, c, _) in R[n]['dev']})
        log(f"        deviating cycle types: {types}; the mechanism is size-specific.")
    f3, f4, f5 = R[3]['frac'], R[4]['frac'], R[5]['frac']
    m2 = (f5 < f4 < f3)
    log(f"  M2  : fraction {f3} ({float(f3):.6f}) > {f4} ({float(f4):.6f}) > "
        f"{f5} ({float(f5):.6f}) -> {'branch (a): FALLING' if m2 else 'branch (b): flat or growing'}")
    cf = all(R[n]['closed_form'] == R[n]['frac'] for n in (3, 4, 5))
    log(f"        derived law (a CONSEQUENCE of the mechanism, not independent "
        f"evidence): fraction = [x^n](1-x)^-1/2 e^-x/2, matching enumeration at "
        f"all three n: {cf}")
    log(f"        that law falls like e^-1/2/sqrt(pi n) ~ 0.342/sqrt(n) -> 0, so the "
        f"selected class vanishes in the limit rather than stalling at a constant.")
    n1w = [R[n]['worlds'] for n in (3, 4, 5)]
    n1o = [R[n]['orbits'] for n in (3, 4, 5)]
    sat = n1o[2] <= n1o[1] <= n1o[0]
    log(f"  N1  : worlds {n1w} vs gauge orbits {n1o}; worlds/orbits "
        f"{[round(w / o, 1) for w, o in zip(n1w, n1o)]}")
    log(f"        orbits {'SATURATE' if sat else 'GROW'} against growing worlds -> "
        f"{'POSITIVE evidence for the no-selector null' if sat else 'no positive support for S5'}; "
        f"but the resolvable fraction collapses {n1o[0]}/{n1w[0]} -> {n1o[2]}/{n1w[2]}, "
        f"so the CEILING on any Ω-internal selector loosens far slower than the world count.")
    s6ok = all(R[n]['s6']['scrambler'] for n in (3, 4, 5))
    onec = all(R[n]['s6']['is_onecycle'] for n in (3, 4, 5))
    coin = [R[n]['s6']['readings_coincide'] for n in (3, 4, 5)]
    log(f"  N2  : S6 argmin orders per n: "
        f"{[R[n]['s6']['argmin_orders'] for n in (3, 4, 5)]} vs family max order "
        f"{[R[n]['s6']['maxord'] for n in (3, 4, 5)]}")
    log(f"        the map's advance prediction, as OPERATIONALISED there "
        f"(minimising accidental closure selects the MAXIMAL-ORDER world), is "
        f"{'CONFIRMED' if s6ok else 'FALSIFIED'} — it holds at n=3,4 and FAILS at "
        f"n=5, where order 10 wins and the family reaches order 12.")
    log(f"        POST-HOC characterisation, recorded as post-hoc and NOT as "
        f"support (rule 6): the argmin is exactly the SINGLE-CYCLE world (the "
        f"micro permutation transitive on all 2n states) at every n: {onec}.")
    log(f"        The two readings of 'maximal scrambler' coincide at n={[3, 4, 5][0]},"
        f"{[3, 4, 5][1]} and SEPARATE at n=5: coincide {coin}. n=5 is the first "
        f"model that could tell them apart, and it did — which is why the "
        f"prediction had to be scored on a family it was not built on.")
    log(f"        the identity is the argMAX at every n: "
        f"{all(R[n]['s6']['identity_is_argmax'] for n in (3, 4, 5))} "
        f"(it closes every view — the stasis pole seen from S6's side).")
    # ---- N3, the RENT-RECORD rider (SELECTOR3_RIDER_N3.md, frozen before this file)
    n3s = {n: R[n]['n3'] for n in (3, 4, 5)}
    allcoll = [(n, c) for n in (3, 4, 5) for c in n3s[n]['collisions']]
    n3_a = all(n3s[n]['all_differ'] for n in (4, 5))
    log(f"  N3  : rent-multiset classes vs orbits: "
        f"{[(n3s[n]['n_spectra'], n3s[n]['n_orbits']) for n in (3, 4, 5)]}; "
        f"collisions per n {[len(n3s[n]['collisions']) for n in (3, 4, 5)]}")
    for (nn, c) in allcoll:
        log(f"        n={nn}: cycle types {c['a'][0]}/{c['b'][0]} — macro periods "
            f"{c['per']}, {'EQUAL >>> branch (b)' if c['equal_period'] else 'DIFFERENT'}; "
            f"view-indexed profile up to gauge separates: "
            f"{'OWED (n=5 lattice)' if c['view_separates'] is None else c['view_separates']}")
    if not allcoll:
        log("        no collisions at any n — the gate has nothing to score "
            "(VOID for lack of an object, not a pass)")
    rec = all(n3s[n]['all_recoverable'] for n in (3, 4, 5))
    reccomp = all(n3s[n]['recoverable_computed'] for n in (3, 4, 5))
    eqp = [(nn, c) for (nn, c) in allcoll if c['equal_period'] and nn in (4, 5)]
    log(f"        -> {'branch (a)' if n3_a else 'branch (b)'} at n=4 and n=5"
        f" (n=3 is the derivation the conjecture was read from, not evidence)")
    if not n3_a:
        log(f"        the conjecture is DEAD as staked.  {len(eqp)} collisions merge "
            f"worlds of EQUAL macro period, so the residue the frame-free summary "
            f"loses is NOT always motion-memory:")
        for (nn, c) in eqp:
            log(f"          n={nn}: cycle types {c['a'][0]} vs {c['b'][0]}, "
                f"both macro period {c['per'][0]} — same motion, different world")
        log(f"        The surviving weaker reading, stated as a reading and NOT as "
            f"a result: every equal-period collision pairs cycle types with the "
            f"SAME number of moved fibers but a different partition of them, so "
            f"the lost bit is how the motion is DIVIDED, not whether it exists.")
    log(f"        recoverability half (the FULL view-indexed profile up to gauge, "
        f"not a coarsening): every collision separated at n=3,4,5: {rec}; computed "
        f"at every n: {reccomp}.")
    log(f"        So the frame-free summary loses distinctions at every size while "
        f"the frame-KEEPING profile loses none — the rider's second half survives "
        f"its own first half's death, and is the part worth carrying.")
    log(f"  plants: (i) stasis {'FIRES' if all(R[n]['p1'] for n in (3, 4, 5)) else 'MISSED'} "
        f"— the identity's generated acts collapse to the identity map at every n, "
        f"so it fails on emptiness of ACTION, not of structure")
    log(f"          (ii) theorem control {'FIRES' if all(R[n]['p2'] for n in (3, 4, 5)) else 'MISSED'} "
        f"— the view-aligned vocabulary separates nothing at every n: |Ident| is "
        f"exactly the macro class {[2 ** n for n in (3, 4, 5)]} (Break.lean T3, live)")

    plants = all(R[n]['p1'] and R[n]['p2'] for n in (3, 4, 5))
    n3void = not allcoll
    log()
    log("D.  VERDICT")
    log("-" * 78)
    if VOID:
        log("  VOID — the instrument is not valid:")
        for v in VOID:
            log(f"    - {v}")
        rc = 1
    elif not plants:
        log("  VOID — a plant failed to fire.")
        rc = 1
    elif n3void:
        log("  VOID — N3 has no collisions to score at any n; the rider's object")
        log("  does not exist in this family and the gate cannot be read either way.")
        rc = 1
    elif m1 and m2 and n3_a:
        log("  M1 branch (a) AND M2 branch (a).  The observer-bootstrap mechanism")
        log("  was staked before the instrument existed and holds across every")
        log("  macro cycle type at n = 4 and n = 5, and the selected fraction")
        log("  falls at every step with a derived law going to zero.  This is the")
        log("  programme's first rule-6 support for an Ω-internal SELECTION")
        log("  principle.  It does not select our universe and does not claim to;")
        log("  what it establishes is that a selector exists which excludes stasis")
        log("  by criterion and narrows as the model grows.")
        log("  N3 branch (a) as well: every rent-multiset collision at n = 4 and")
        log("  n = 5 merges worlds of DIFFERENT macro period, so the residue the")
        log("  frame-free summary loses is motion-memory — the Record coordinate")
        log("  recurring in Ω's cost face, staked in the rider before this file.")
        rc = 0
    else:
        log(f"  M1 {'(a)' if m1 else '(b)'}, M2 {'(a)' if m2 else '(b)'}, "
            f"N3 {'(a)' if n3_a else '(b)'} — a MIXED result, reported as one.")
        if m1 and m2:
            log("  SELECTOR-3's OWN gates both passed: the observer-bootstrap")
            log("  mechanism was staked before this instrument existed, holds across")
            log("  every macro cycle type at n = 4 and n = 5, and the selected")
            log("  fraction falls at every step under a derived law going to zero.")
            log("  That is the programme's first rule-6 support for an Ω-internal")
            log("  SELECTION principle, and it stands.")
        if not n3_a:
            log("  The RIDER died: N3's RENT-RECORD conjecture is falsified as")
            log("  staked, by equal-period collisions at BOTH n = 4 and n = 5, named")
            log("  above.  The rider is separable — it kills itself and touches")
            log("  neither M1 nor M2 nor S3's ranking.")
        rc = 2
    log()
    log(f"  exit {rc}  (0 = gates passed and plants fired; 2 = valid run, staked "
        f"gate killed; 1 = instrument invalid)")
    LOG.close()
    sys.exit(rc)


if __name__ == "__main__":
    main()
