#!/usr/bin/env python3
"""SELECTOR-4 — the bootstrap gauntlet on GAUGE WORLDS, scale-indexed by acuity.

Implements conformance/omega/SELECTOR4_PREREG.md.  Exact throughout (integer
permutation arithmetic; no floats enter any decision).  Machinery reused from
conformance/gravity/{binary_groups,bridge1}.py.

================================ THE THREE CONSTRUCTIONS THE FREEZE DELEGATES

The freeze fixes the worlds, the ladder and the gates, and delegates to this
instrument (a) the act vocabulary per rung, (b) the candidate family, and
(c) nothing else.  Both are stated here in full, with the measurement that
forced each choice, because a delegated degree of freedom that is not written
down is a fitted parameter.

--- (1) THE ACUITY LADDER, cumulative.
A finer observer sees everything a coarser one sees plus its own reading, so
rung k's view is the JOIN of readings 0..k:
  A0 blind      : the one-point view
  A1 flatness   : A0 v [a,b]==e
  A2 mass       : A1 v conjugacy class of the puncture holonomy [a,b]
  A3 classes    : A2 v (class a, class b)
  A4 orbit      : A3 v the simultaneous-conjugation orbit label (ADM channel)
Read non-cumulatively the ladder is NOT a chain — (class a, class b) does not
determine the class of [a,b].  The join makes it one, and B0 verifies the chain
exactly rather than assuming it.

--- (2) THE ACT VOCABULARY: invariant partial sections.
SELECTOR-3's discipline: an act is generated by a subsystem that is (i) closed
under the dynamics, (ii) definable from (view, dyn) alone, (iii) NOT
view-covariant — else Break.lean's T3 makes it provably powerless.  There it
was a T-invariant transversal (exactly one state per fiber).

THE LITERAL TRANSPLANT IS EMPTY, and this was measured before the vocabulary
was chosen: the mapping-class step admits ZERO invariant transversals at every
rung above A0, for ALL FOUR groups (D4/2T/2O/2I).  The obstruction is
arithmetic — at A1 a transversal would need two fixed points in different
fibers or a 2-cycle spanning them, and the step has exactly one fixed point and
no 2-cycles.  A vocabulary that is empty everywhere cannot be scored, so the
discipline is generalized at exactly one point:

    P is an INVARIANT PARTIAL SECTION at acuity Ak when P is a union of
    T-cycles meeting each Ak-fiber AT MOST once ("exactly once" relaxed to
    "at most once").  Its act is  a_P(s) = T(s) for s in P, s otherwise.

The atomic generators are the fiber-injective T-cycles.  This is a strict
GENERALIZATION, not a replacement: for disjoint invariant P, Q one has
a_{P∪Q} = a_P ∘ a_Q  (s in P: a_Q fixes it, a_P sends it to Ts; s in Q:
a_Q sends it to Ts which stays in Q so a_P fixes it; s outside: fixed) — so
every full-section act of SELECTOR-3 is a WORD in these generators, and the
generated monoid contains SELECTOR-3's vocabulary whenever it is non-empty.
Each a_P is a bijection (T permutes the invariant set P, identity off it).

Two consequences are structural, not lucky, and they are what makes plants
(i) and (iii) fire BY CONSTRUCTION:
  * at A0 the only fiber is everything, so a fiber-injective cycle has length
    one, so a_P = identity: the blind rung's vocabulary is trivial (plant iii);
  * the identity world's cycles are all singletons and a_P = identity for every
    P: stasis fails on emptiness of ACTION, never of structure (plant i).

DISCLOSED SENSITIVITY: this vocabulary is strictly larger than SELECTOR-3's on
SELECTOR-3's own model, so it is a DIFFERENT act-relative identity, and
Break.lean makes identity act-relative by design.  Whether SELECTOR-3's verdict
survives the generalization is computed and reported here as a scope note; it
is NOT a re-run of SELECTOR-3, whose record stands with its own declared
vocabulary.

--- (3) THE CANDIDATE FAMILY, and why it is restricted.
|G| * ord(step) is 48 / 1152 / 6912 / 1008000 — the last is infeasible, so the
freeze's escape clause is taken and the family is declared:

    F(G) = { gauge_r o step^d : d | ord(step), r a conjugacy-class rep of G }

one canonical generator per CYCLIC SUBGROUP of the dynamics group <step>
(the divisors), dressed by one representative per GAUGE ORBIT of the dressing
(the classes).  That is 20 / 70 / 120 / 540 labels, which collapse to
16 / 60 / 105 / 480 DISTINCT permutations once deduplicated.  It contains the
identity
(d = ord(step), r = e) — plant (i)'s carrier — and the step itself (d = 1,
r = e).  Nothing else is in it, and no word-length or size knob appears.
|Ident| is constant on gauge classes (the views are gauge-invariant and the
step commutes with the gauge action), so each member is already a distinct
gauge representative and no further reduction is available.

--- SEPARATION, exact and with no word-length cut.
For a home T and a candidate T', the pair-BFS from the diagonal reaches
exactly the graphs of the permutations  rho_w = w[T'] o w[T]^-1, so the pair
relation is closed by iterating on rho instead of on 14400^2 = 2*10^8 pairs:
  step letter : rho -> T' o rho o T^-1
  knob letter : rho -> a o rho o a^-1      (the same act on both sides)
starting at rho = identity, and T is separated from T' iff SOME reachable rho
fails to preserve the view.  Words beginning with knobs give rho = id, so the
first informative word is the single step, whose test reduces to
  view o T' == view o T,
which is why candidates are first grouped by that array: only within a group
can anything be indistinguishable, and only those pairs pay for a BFS.  A node
budget is declared; exhausting it VOIDs that pair rather than guessing.

EXIT CONTRACT: 0 = no gate killed and all plants fired; 2 = valid instrument,
a staked gate landed on branch (b); 1 = instrument invalid (VOID, internal
inconsistency, missed plant).

Credits: the acuity principle is the lead's formulation of 2026-08-28; Wilson
and Kadanoff for effective-theory nesting; Break.lean's T3 for the powerless
half; SELECTOR-3's record for the criterion's mechanism.
"""
import sys
import time
import numpy as np

sys.path.insert(0, "/home/emoore/CIRISHolon/conformance/gravity")

LOG = open(__file__.replace(".py", ".log"), "w")
VOID = []
CTRL_SAMPLE = 8           # plant (ii): candidates scored per carrier (T3 is the proof)
BUDGET = 2000             # rho-BFS node budget per pair; exhaustion VOIDs the CELL
                          # (2000 x 57 kB keeps the search inside ~114 MB at 2I)


def log(s=""):
    print(s)
    LOG.write(s + "\n")
    LOG.flush()


def void(cond, msg):
    if not cond:
        VOID.append(msg)
    return cond


# ============================================================ the four worlds
def load_groups():
    import binary_groups as BG
    from bridge1 import MUL as D4MUL, INV as D4INV
    out = {"D4": (np.array(D4MUL), np.array(D4INV))}

    def grp(elems, rmul, val, ring, name):
        G = BG.Grp(name, elems, rmul, val, ring)
        return (np.array(G.MUL), np.array(G.INV))
    out["2T"] = grp(BG.hurwitz_scaled(), BG.mul_sqrt2, BG.VAL_SQRT2, "Z", "2T")
    e, r, v, ring = BG.build_2O()
    out["2O"] = grp(e, r, v, ring, "2O")
    e, r, v, ring = BG.build_2I()
    out["2I"] = grp(e, r, v, ring, "2I")
    return out


def refines(fine, coarse):
    m = {}
    for f, c in zip(fine.tolist(), coarse.tolist()):
        if m.setdefault(f, c) != c:
            return False
    return True


def build_world(name, MUL, INV):
    n = MUL.shape[0]
    N = n * n
    A = np.arange(N) % n
    B = np.arange(N) // n
    IDX = lambda a, b: a + n * b
    ident_g = int(next(g for g in range(n) if (MUL[g] == np.arange(n)).all()))

    comm = MUL[MUL[A, B], MUL[INV[A], INV[B]]]
    CLS = np.full(n, -1)
    reps, lab = [], 0
    for g in range(n):
        if CLS[g] >= 0:
            continue
        for h in {int(MUL[MUL[x, g], INV[x]]) for x in range(n)}:
            CLS[h] = lab
        reps.append(g)
        lab += 1
    ncls = lab

    T_MAP = IDX(A, MUL[A, B])
    S_MAP = IDX(B, MUL[MUL[B, A], INV[B]])
    step = S_MAP[T_MAP].astype(np.int32)
    void(len(set(step.tolist())) == N, f"{name}: the step is not bijective")

    orb = np.full(N, -1)
    lab = 0
    for i in range(N):
        if orb[i] >= 0:
            continue
        stack = [i]
        while stack:
            j = stack.pop()
            if orb[j] >= 0:
                continue
            orb[j] = lab
            a, b = int(A[j]), int(B[j])
            for x in range(n):
                k = int(IDX(MUL[MUL[x, a], INV[x]], MUL[MUL[x, b], INV[x]]))
                if orb[k] < 0:
                    stack.append(k)
        lab += 1

    R = [np.zeros(N, np.int64), (comm == ident_g).astype(np.int64), CLS[comm],
         CLS[A] * ncls + CLS[B], orb]

    def join(k):
        key, out = {}, np.zeros(N, np.int64)
        for i in range(N):
            t = tuple(int(R[j][i]) for j in range(k + 1))
            if t not in key:
                key[t] = len(key)
            out[i] = key[t]
        return out
    V = [join(k) for k in range(5)]
    for k in range(4):
        void(refines(V[k + 1], V[k]),
             f"{name}: acuity ladder is not a chain of coarsenings at A{k}->A{k+1}")

    GAUGE = [IDX(MUL[MUL[g, A], INV[g]], MUL[MUL[g, B], INV[g]]).astype(np.int32)
             for g in range(n)]
    for g in range(n):
        void(len(set(GAUGE[g].tolist())) == N, f"{name}: gauge action not bijective")

    ordstep, x, idp = 1, step.copy(), np.arange(N, dtype=np.int32)
    while not np.array_equal(x, idp):
        x = step[x]
        ordstep += 1
    return dict(name=name, n=n, N=N, step=step, V=V, GAUGE=GAUGE, reps=reps,
                ncls=ncls, ordstep=ordstep, idp=idp, ident_g=ident_g)


def divisors(m):
    return sorted(d for d in range(1, m + 1) if m % d == 0)


def family(W):
    """The declared candidate family: one canonical generator per cyclic
    subgroup of <step>, dressed by one representative per gauge orbit."""
    out, seen = [], set()
    powers = {}
    for d in divisors(W["ordstep"]):
        x = W["idp"].copy()
        for _ in range(d):
            x = W["step"][x]
        powers[d] = x.astype(np.int32)
    for d in divisors(W["ordstep"]):
        for r in W["reps"]:
            perm = W["GAUGE"][r][powers[d]].astype(np.int32)
            key = perm.tobytes()
            if key in seen:
                continue
            seen.add(key)
            out.append(((d, r), perm))
    return out


# ==================================================== acts and the separation
def cycles_of(perm, N):
    seen = np.zeros(N, bool)
    out = []
    pl = perm.tolist()
    for i in range(N):
        if seen[i]:
            continue
        c, j = [], i
        while not seen[j]:
            seen[j] = True
            c.append(j)
            j = pl[j]
        out.append(c)
    return out


def knobs_partial_sections(perm, view, N):
    """The atomic acts: fiber-injective cycles of the dynamics.

    Returned SPARSELY, as the carrier cycles themselves plus a per-state cycle
    label, never as materialised permutations.  a_P is the identity off P, so
    conjugating by it touches only P and rho^-1(P) — O(|P|) instead of O(N) —
    and since the cycles are DISJOINT, expanding every act at a search node
    costs O(N) in total rather than O(N x #acts).  At 2I's A4 that is the
    difference between 7680 arrays of 14400 int32 (442 MB, and 3 s per pair)
    and one label array.  The ACTS are unchanged; only the representation is."""
    vl = view.tolist()
    cyc_id = np.full(N, -1, dtype=np.int32)
    out = []
    for c in cycles_of(perm, N):
        if len(c) == 1:
            continue          # a fixed point's act IS the identity: no new words
        fs = [vl[s] for s in c]
        if len(set(fs)) == len(fs):
            arr = np.array(c, dtype=np.int32)
            cyc_id[arr] = len(out)
            out.append(arr)
    return out, cyc_id


def knobs_view_aligned(perm, view, N):
    """Plant (ii)'s control vocabulary: apply the dynamics on one CYCLE of view
    blocks, identity elsewhere.  A single block is NOT usable — the dynamics
    carries it off itself, so 'apply T on one block' is not a bijection and the
    rho-closure (which inverts acts) would be reading garbage.  A cycle of
    blocks under the induced block permutation IS invariant, so the act is a
    bijection, and it is view-covariant (its block action is that cycle), hence
    gauge-safe by Break.lean T3 wherever the dynamics is closed."""
    nb = int(view.max()) + 1
    blk = {}
    for a_, b_ in zip(view.tolist(), view[perm].tolist()):
        blk.setdefault(a_, b_)
    out, seen = [], set()
    for b in range(nb):
        if b in seen:
            continue
        cyc, j = [], b
        while j not in seen:
            seen.add(j)
            cyc.append(j)
            j = blk.get(j, j)
        m = np.isin(view, np.array(cyc))
        a = np.arange(N, dtype=np.int32)
        a[m] = perm[m]
        out.append(a.astype(np.int32))
    return out


def inv_perm(p, N):
    q = np.empty(N, dtype=np.int32)
    q[p] = np.arange(N, dtype=np.int32)
    return q


def all_bijective(perms, N):
    return all(len(set(p.tolist())) == N for p in perms)


def acts_are_bijections(cycles, perm):
    """a_P is a bijection exactly when P is T-invariant; the carriers are
    T-cycles, so this is checked rather than assumed (M-NONBIJECTIVE-STEP)."""
    return all(np.array_equal(np.sort(perm[c]), np.sort(c)) for c in cycles)


def separates(act, T, Tp, view, N, idp):
    """Exact over ALL experiment words (the rho-closure), no length cut.

    `act` is (cycles, cyc_id, Tinv) for the HOME world.  Returns True/False, or
    None if the declared node budget is exhausted (VOID, never a guess)."""
    if int(view.max()) == 0:
        return False                      # a constant view separates nothing, ever
    if not np.array_equal(view[Tp], view[T]):
        return True                       # the single-step word already splits
    cycles, cyc_id, Tinv = act
    if not cycles:
        # EMPTY VOCABULARY.  The closure is then the chain rho_k = T'^k T^-k, so
        # separation reduces to  exists k >= 1 : view o T'^k != view o T^k.
        a, b, k = T, Tp, 1
        while k < BUDGET:
            if not np.array_equal(view[a], view[b]):
                return True
            if np.array_equal(a, idp) and np.array_equal(b, idp):
                return False
            a, b, k = T[a], Tp[b], k + 1
        return None
    seen = {idp.tobytes()}
    stack = [idp]
    while stack:
        rho = stack.pop()
        if not np.array_equal(view[rho], view):
            return True
        nxt = [Tp[rho[Tinv]]]
        rhoinv = inv_perm(rho, N)
        for ci, P in enumerate(cycles):
            # rho' = a_P o rho o a_P^-1 differs from rho only on P u rho^-1(P)
            xs = np.unique(np.concatenate((P, rhoinv[P])))
            y = np.where(cyc_id[xs] == ci, Tinv[xs], xs)
            z = rho[y]
            newv = np.where(cyc_id[z] == ci, T[z], z)
            if np.array_equal(newv, rho[xs]):
                continue                  # the act commutes with rho
            r = rho.copy()
            r[xs] = newv
            nxt.append(r)
        for r in nxt:
            k = r.tobytes()
            if k not in seen:
                if len(seen) >= BUDGET:
                    return None
                seen.add(k)
                stack.append(r)
    return False


def separates_dense(knobs, T, Tp, view, N, idp):
    """The same exact rho-closure for plant (ii)'s materialised control acts,
    whose carriers are unions of view blocks rather than single cycles."""
    if not np.array_equal(view[Tp], view[T]):
        return True
    Tinv = inv_perm(T, N)
    kinv = [inv_perm(a, N) for a in knobs]
    seen = {idp.tobytes()}
    stack = [idp]
    while stack:
        rho = stack.pop()
        if not np.array_equal(view[rho], view):
            return True
        nxt = [Tp[rho[Tinv]]] + [a[rho[ai]] for a, ai in zip(knobs, kinv)]
        for r in nxt:
            k = r.tobytes()
            if k not in seen:
                if len(seen) >= BUDGET:
                    return None
                seen.add(k)
                stack.append(r)
    return False


def closed_at(perm, view):
    """Is the dynamics closed at this view (rent zero)?"""
    m = {}
    for a, b in zip(view.tolist(), view[perm].tolist()):
        if m.setdefault(a, b) != b:
            return False
    return True


# =========================================================== the per-rung run
def pow_step(W, j):
    x = W["idp"].copy()
    for _ in range(j):
        x = W["step"][x]
    return x


def gauge_invariant_view(view, GAUGE):
    return all(np.array_equal(view[g], view) for g in GAUGE)


def run_rung(W, fam, k, want_control):
    view = W["V"][k]
    N = W["N"]
    idp = W["idp"]
    # An empty-vocabulary verdict depends only on the two step-powers, because
    # the view is gauge-invariant and the gauge commutes with the step — both
    # CHECKED here, never assumed.  That collapses 480x480 pairs to at most
    # (#divisors)^2 distinct questions at the coarse rungs, where the vocabulary
    # is empty and the rho-chain is otherwise thousands of nodes long.
    if int(view.max()) == 0:
        # A0, analytically: one block, so no rho can ever fail to preserve the
        # view and nothing is separable.  |Ident| is the whole family and the
        # selected set is empty -- computed here as a fact, not skipped.
        return dict(sel=[], idents={i: list(range(len(fam))) for i in range(len(fam))},
                    voids=0, ngroups=1, maxgroup=len(fam), ctrl_ok=True,
                    ctrl_n=1, ctrl_scored=0, knobcounts={})
    ginv = gauge_invariant_view(view, W["GAUGE"])
    # With a gauge-invariant view, view o (gauge_r step^d)^k = view o step^(dk),
    # so the whole empty-vocabulary chain is a function of the step-power alone.
    # Canonicalise the readings view o step^j ONCE per rung (exact ids, not
    # hashes) and every such verdict becomes an integer comparison.
    seqids = None
    if ginv:
        L = W["ordstep"]
        idmap, seqids = {}, []
        x = idp.copy()
        for _ in range(L):
            b = view[x].tobytes()
            seqids.append(idmap.setdefault(b, len(idmap)))
            x = W["step"][x]
        # view o T^k = view o step^(dk) follows from the two facts already
        # checked above (the gauge commutes with the step, and the view is
        # gauge-blind).  It is load-bearing, so it is also CHECKED directly on a
        # sample — by canonical id, which costs one lookup rather than a
        # from-scratch power.
        for (lab, q) in fam[:4]:
            d, acc = lab[0], idp.copy()
            for kk in range(1, 4):
                acc = q[acc]
                got = idmap.get(view[acc].tobytes(), -1)
                void(got == seqids[(d * kk) % L],
                     f"{W['name']} A{k}: view o T^k != view o step^(dk)")
    void(ginv, f"{W['name']} A{k}: the view is not gauge-invariant")
    void(all(np.array_equal(g[W["step"]], W["step"][g]) for g in W["GAUGE"]),
         f"{W['name']}: the gauge action does not commute with the step")
    dcache = {}
    # group by the single-step reading: only within a group can anything be
    # indistinguishable, so only those pairs pay for a BFS
    groups = {}
    for i, (lab, p) in enumerate(fam):
        groups.setdefault(view[p].tobytes(), []).append(i)

    idents, voids = {}, 0
    knobcache = {}
    for key, members in groups.items():
        if len(members) == 1:
            idents[members[0]] = [members[0]]
            continue
        for i in members:
            if i not in knobcache:
                cyc, cid = knobs_partial_sections(fam[i][1], view, N)
                void(acts_are_bijections(cyc, fam[i][1]),
                     "an act carrier is not dynamics-invariant (act not bijective)")
                knobcache[i] = (cyc, cid, inv_perm(fam[i][1], N))
            out = []
            for j in members:
                if i == j:
                    out.append(j)
                    continue
                if ginv and not knobcache[i][0]:
                    key = (fam[i][0][0], fam[j][0][0])
                    if key not in dcache:
                        L = W["ordstep"]
                        d1, d2 = key
                        dcache[key] = any(
                            seqids[(d1 * kk) % L] != seqids[(d2 * kk) % L]
                            for kk in range(1, L + 1))
                    s = dcache[key]
                else:
                    s = separates(knobcache[i], fam[i][1], fam[j][1], view, N, idp)
                if s is None:
                    voids += 1
                    out.append(j)          # undecided; the CELL is voided below
                elif not s:
                    out.append(j)
            idents[i] = out
    sel = sorted(i for i in range(len(fam)) if len(idents[i]) == 1)

    # plant (ii): the T3 control, on the pairs where the dynamics IS closed
    ctrl_ok, ctrl_n, ctrl_scored = True, 0, 0
    if want_control:
        for i, (lab, p) in enumerate(fam):
            if not closed_at(p, view):
                continue
            same = [j for j, (l2, q) in enumerate(fam)
                    if np.array_equal(view[q], view[p])]
            if len(same) < 2:
                continue                   # vacuous sector; not a carrier
            ctrl_n += 1
            kv = knobs_view_aligned(p, view, N)
            void(all_bijective(kv, N), "a view-aligned control act is not bijective")
            # The PROOF that this vocabulary is powerless is Break.lean's T3; the
            # plant is a live CONTROL, so it is scored on a declared bounded
            # sample of the carrier's class (the whole class would be 480 dense
            # closures run to exhaustion at 2I, since T3 guarantees every one of
            # them terminates only by exhausting).
            for j in same[:CTRL_SAMPLE]:
                if separates_dense(kv, p, fam[j][1], view, N, idp):
                    ctrl_ok = False
            ctrl_scored += min(len(same), CTRL_SAMPLE)
            break                          # one carrier with a nonzero sector
    return dict(sel=sel, idents=idents, voids=voids, ngroups=len(groups),
                maxgroup=max(len(v) for v in groups.values()),
                ctrl_ok=ctrl_ok, ctrl_n=ctrl_n, ctrl_scored=ctrl_scored,
                knobcounts={i: len(knobcache[i][0]) for i in knobcache})


def main():
    log("=" * 78)
    log("SELECTOR-4 — the bootstrap gauntlet on gauge worlds, scale-indexed")
    log("prereg: conformance/omega/SELECTOR4_PREREG.md (frozen before this file)")
    log("=" * 78)
    log()
    log("A.  DECLARED CONSTRUCTIONS (the freeze's delegated degrees of freedom)")
    log("-" * 78)
    log("    acuity ladder : cumulative joins A0<A1<A2<A3<A4 (chain verified, B0)")
    log("    act vocabulary: invariant PARTIAL sections (fiber-injective cycles).")
    log("                    Forced: the literal SELECTOR-3 transversal rule gives")
    log("                    ZERO sections above A0 on all four groups (measured).")
    log("    family        : {gauge_r o step^d : d | ord(step), r a class rep}")
    log("    separation    : exact rho-closure, no word-length cut, budget "
        f"{BUDGET}")
    log()

    Gs = load_groups()
    R = {}
    for name in ("D4", "2T", "2O", "2I"):
        t0 = time.time()
        MUL, INV = Gs[name]
        W = build_world(name, MUL, INV)
        fam = family(W)
        # the literal-transversal measurement that forced the vocabulary
        lit = []
        for k in range(5):
            nb = int(W["V"][k].max()) + 1
            cyc, _ = knobs_partial_sections(W["step"], W["V"][k], W["N"])
            lit.append(len(cyc))
        idx_id = next(i for i, (l, p) in enumerate(fam)
                      if np.array_equal(p, W["idp"]))
        idx_step = next((i for i, (l, p) in enumerate(fam)
                         if np.array_equal(p, W["step"])), None)
        void(idx_step is not None, f"{name}: the step itself is not in the family")

        log(f"B.  {name}   |G|={W['n']}  states={W['N']}  ord(step)={W['ordstep']}"
            f"  family={len(fam)}")
        log("-" * 78)
        log(f"    acuity blocks A0..A4 : {[int(v.max()) + 1 for v in W['V']]}")
        log(f"    fiber-injective cycles of the step per rung : {lit}")
        rungs = []
        for k in range(5):
            tk = time.time()
            r = run_rung(W, fam, k, want_control=True)
            rungs.append(r)
            log(f"    A{k}: selected {len(r['sel']):4d}/{len(fam)} = "
                f"{len(r['sel']) / len(fam):.4f}   groups={r['ngroups']:4d} "
                f"(max {r['maxgroup']:3d})   voids={r['voids']}"
                f"   [{time.time() - tk:.1f}s]")
        R[name] = dict(W=W, fam=fam, rungs=rungs, idx_id=idx_id, lit=lit,
                       secs=time.time() - t0)

        log(f"    [total {R[name]['secs']:.1f}s]")
        log()

    # ------------------------------------------------------------ the gates
    log("C.  VERDICTS")
    log("-" * 78)
    names = ("D4", "2T", "2O", "2I")
    b0 = not VOID
    log(f"  B0  : {'PASS' if b0 else 'VOID'} — step and gauge action bijective on "
        f"all four worlds; the acuity ladder verified a chain of coarsenings at "
        f"every rung; identity sets by the exact rho-closure (pair-BFS reorganised)")
    tv = sum(r["voids"] for n in names for r in R[n]["rungs"])
    log(f"        budget exhaustions (VOID pairs): {tv}")

    voidcells = [(n, k) for n in names for k in range(5)
                 if R[n]["rungs"][k]["voids"] > 0]
    g1rows = []
    for n in names:
        for k in range(5):
            s = len(R[n]["rungs"][k]["sel"])
            f = len(R[n]["fam"])
            g1rows.append((n, k, s, f))
    if voidcells:
        log(f"        VOIDED CELLS (budget exhausted, verdict refused): {voidcells}")
        log("        A voided cell is excluded from EVERY gate below, not just G1:")
        log("        its selected count is reported for information and carries no")
        log("        verdict, because an undecided pair could only ever ADD to a")
        log("        world's identity set, so the printed count is a lower bound.")
    g1rows = [(n, k, s, f) for (n, k, s, f) in g1rows if (n, k) not in voidcells]
    proper = [(n, k, s, f) for (n, k, s, f) in g1rows if 0 < s < f]
    g1 = len(proper) > 0
    log(f"  G1  : (G, Ak) cells selecting a PROPER NONEMPTY subset: {len(proper)}/20"
        f" -> {'branch (a)' if g1 else 'branch (b)'}")
    for (n, k, s, f) in proper[:12]:
        log(f"        {n} A{k}: {s}/{f}")
    if not g1:
        log("        every rung selects everything-or-nothing: the principle's reach")
        log("        STOPS at fiber toys — a scope boundary, banked as such.")

    log("  Z1  : selected-set sizes along A1->A4 (the zoom law, staked "
        "NON-INCREASING)")
    z1 = True
    invs = []
    for n in names:
        sizes = [len(R[n]["rungs"][k]["sel"]) for k in range(5)]
        sets_ = [set(R[n]["rungs"][k]["sel"]) for k in range(5)]
        mono = all(sizes[k + 1] <= sizes[k] for k in range(1, 4))
        nest = all(sets_[k + 1] <= sets_[k] for k in range(1, 4))
        if not mono:
            z1 = False
            for k in range(1, 4):
                if sizes[k + 1] > sizes[k]:
                    invs.append((n, k))
        log(f"        {n}: {sizes}  monotone-non-increasing(A1..A4)={mono}"
            f"  nested={nest}")
    log(f"        -> {'branch (a)' if z1 else 'branch (b)'}")
    if not z1:
        log(f"        INVERSIONS at {invs}.")
        log("        The direction is forced by the declared construction and was")
        log("        derivable before the run: refining the view refines the")
        log("        fiber-injectivity test, so BOTH the view and the vocabulary")
        log("        grow with acuity, separation is monotone, |Ident| is")
        log("        non-increasing and the SELECTED set is non-DEcreasing.  The")
        log("        monotone quantity the lead's intuition names is |Ident|; the")
        log("        passing set moves the other way.  Z1 is therefore a statement")
        log("        about which quantity nests, and as staked it is false here.")

    log("  F1  : selected fraction at each rung, per group (group discrimination)")
    for k in range(5):
        cells = []
        for n in names:
            v = len(R[n]["rungs"][k]["sel"]) / len(R[n]["fam"])
            cells.append(f"{n}={v:.4f}" + ("[VOID]" if (n, k) in voidcells else ""))
        log(f"        A{k}: " + "  ".join(cells))
    f1 = any(len({round(len(R[n]["rungs"][k]["sel"]) / len(R[n]["fam"]), 9)
                  for n in names if (n, k) not in voidcells}) > 1 for k in range(5))
    log("        (decided cells only; VOID cells carry no verdict)")
    log(f"        -> {'branch (a): the criterion DISCRIMINATES gauge structures' if f1 else 'branch (b): group-blind on this family'}")

    log("  FR1 : finest rung (A4) fraction across |G| = 8, 24, 48, 120")
    row = [(R[n]["W"]["n"], len(R[n]["rungs"][4]["sel"]), len(R[n]["fam"]))
           for n in names]
    for nm, (g, s, f) in zip(names, row):
        vd = "   VOID — lower bound only, no verdict" if (nm, 4) in voidcells else ""
        log(f"        |G|={g:3d}: {s}/{f} = {s / f:.4f}{vd}")
    log("        The sequence is COMPLETE only for |G| = 8, 24, 48; the |G| = 120")
    log("        entry is undecided at the declared budget and is not a data point.")
    log("        any law fitted to four points is POST-HOC by the freeze's own")
    log("        honesty clause; none was derived in advance and none is claimed.")

    p1 = all(len(R[n]["rungs"][k]["idents"].get(R[n]["idx_id"], [0, 1])) != 1
             for n in names for k in range(5))
    p1acts = True
    for n in names:
        W, fam = R[n]["W"], R[n]["fam"]
        for k in range(5):
            cyc, _ = knobs_partial_sections(fam[R[n]["idx_id"]][1], W["V"][k], W["N"])
            if len(cyc) != 0:
                p1acts = False
    p3 = all(len(R[n]["rungs"][0]["sel"]) == 0 for n in names)
    p3acts = True
    for n in names:
        W, fam = R[n]["W"], R[n]["fam"]
        for (lab, p) in fam:
            cyc, _ = knobs_partial_sections(p, W["V"][0], W["N"])
            if len(cyc) != 0:
                p3acts = False
    p2 = all(r["ctrl_ok"] for n in names for r in R[n]["rungs"])
    p2n = sum(r["ctrl_n"] for n in names for r in R[n]["rungs"])
    void(p2n > 0, "plant (ii) has no carrier with a nonzero sector — vacuous")
    log(f"  plants: (i) stasis {'FIRES' if p1 and p1acts else 'MISSED'} — the identity "
        f"fails at every rung of every group, and its generated acts are all the "
        f"identity map (emptiness of ACTION, not of structure)")
    log(f"          (ii) T3 control {'FIRES' if p2 else 'MISSED'} — the view-aligned "
        f"vocabulary separates nothing on closed views; carriers {p2n}, "
        f"candidate pairs scored {sum(r['ctrl_scored'] for n in names for r in R[n]['rungs'])}")
    log(f"          (iii) blind rung {'FIRES' if p3 and p3acts else 'MISSED'} — at A0 "
        f"every act is the identity map for every world, and NOTHING is selected "
        f"in any group")

    plants = p1 and p1acts and p2 and p3 and p3acts
    log()
    log("D.  VERDICT")
    log("-" * 78)
    if VOID:
        log("  VOID — the instrument is not valid:")
        for v in VOID[:10]:
            log(f"    - {v}")
        rc = 1
    elif not plants:
        log("  VOID — a plant failed to fire.")
        rc = 1
    elif g1 and z1 and f1:
        log("  G1 (a), Z1 (a), F1 (a): the gauntlet's rung 2 passed in full.")
        rc = 0
    else:
        log(f"  MIXED: G1 {'(a)' if g1 else '(b)'}, Z1 {'(a)' if z1 else '(b)'}, "
            f"F1 {'(a)' if f1 else '(b)'} — each banked at its exact strength.")
        log("  What no outcome here claims: leptons, groups-of-nature, kinematics,")
        log("  constants.  The chain's rungs 3-4 remain open regardless.")
        rc = 2
    log()
    log(f"  exit {rc}  (0 = all gates passed and plants fired; 2 = valid run, a "
        f"staked gate killed; 1 = instrument invalid)")
    LOG.close()
    sys.exit(rc)


if __name__ == "__main__":
    main()
