"""Write the MIXTURES-1 referee drop the engine's R2 gate reads.

    python3 emit2.py [outdir]

The PER-PAIR emitter is `emit_engine.emit_pair`, reused unchanged: it carries
nine refusals, each of which exists because a real near-miss got past its
absence -- a declared zero uncertainty, an absent spin audit, a state above the
next sector's minimum, a resolution column that defaulted to "resolved
everywhere", exponent notation, mismatched array lengths, a force that is not
repulsive at the innermost geometry. Rewriting that would mean re-earning all
nine.

What is written HERE is the manifest, and only the manifest, because the
manifest is the one part that is campaign-specific by nature: it names the
staked set, and `present + owed = staked` is the invariant the engine's test
enforces. ELEMENTS-1's is a literal list of nine inside `emit_engine.main()`; a
launcher cannot parameterise a literal, and it should not want to -- the staked
set is a fact about a FREEZE, and each freeze should say its own out loud.

TWO THINGS THIS DROP CARRIES THAT ELEMENTS-1'S DOES NOT.

**The D1 bridge marking.** S2 and SiO are the two species where exact FCI and
the q8-mps DMRG route overlap, so they are what the bridge is validated against.
Their files say so in their own headers rather than in a note somewhere else,
because a reference value that does not know it is a reference value gets
regenerated by someone who does not know either.

**A scope line.** The engine now declares elements up to xenon; this referee's
declared model stops at argon. A gate reading "the engine's curves match the
referee" is VACUOUSLY true for any pair the referee cannot compute, so the
manifest states the scope as a fact rather than leaving it to be inferred from
which files happen to be present.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_E1 = os.path.join(HERE, "elements1")
sys.path.insert(0, HERE)
if _E1 not in sys.path:
    sys.path.append(_E1)

import species as SP                                           # noqa: E402
import m1core as M                                             # noqa: E402
import species2 as SP2                                         # noqa: E402
import emit_engine as EE                                       # noqa: E402
import elements_core as EC                                     # noqa: E402

MODEL = "MIXTURES1/STO-3G/FCI"
STAKED = ["Cl2", "S2", "Ar2", "HCl", "ClF", "NaH", "SiO", "NeAr"]
DEFAULT_OUT = os.path.join(HERE, "engine_handoff", "mixtures1")
POTENTIAL = ("elements_potential.json", "elements_potential_partial.json")


def _source():
    for cand in POTENTIAL:
        p = os.path.join(HERE, cand)
        if os.path.exists(p):
            return cand, json.load(open(p))
    return None, None


def _mark_bridge(path, name):
    """Say, in the file itself, that it is the D1 bridge's reference."""
    with open(path) as f:
        obj = json.load(f)
    obj["d1_bridge_reference"] = {
        "role": ("exact-in-model FCI reference for gate D1 of "
                 "MIXTURES1_PREREG.md"),
        "gate": ("q8-mps DMRG ground energies must match these values to "
                 "<= 1e-8 hartree across this grid before any DMRG-only curve "
                 "may enter the sandbox"),
        "kill": ("an overlap disagreement past 1e-8 kills the BRIDGE's "
                 "admission, not this FCI"),
        "precision": ("these are 50-digit exact-in-model values; the 1e-8 gate "
                      "is 40 orders looser than the reference, so a "
                      "disagreement is the DMRG's"),
        "do_not_regenerate_at_lower_precision": True,
    }
    with open(path, "w") as f:
        json.dump(obj, f, indent=1)
    return True


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT
    os.makedirs(outdir, exist_ok=True)

    atoms_p = os.path.join(HERE, "mixtures_atoms.json")
    if not os.path.exists(atoms_p):
        print("gate R1 not run: mixtures_atoms.json is absent")
        return 1
    atoms = json.load(open(atoms_p))
    if atoms.get("model") != MODEL:
        print("mixtures_atoms.json carries model %r, not %r"
              % (atoms.get("model"), MODEL))
        return 2
    p = EE.emit_atoms(atoms, outdir)
    print("wrote %s  (%d symbols)" % (os.path.basename(p), len(SP.ATOMS)))

    src, pot = _source()
    if pot is None:
        print("no assembled curves yet")
        return 1
    if pot.get("model") != MODEL:
        print("%s carries model %r, not %r -- run curves2.py, which restamps it"
              % (src, pot.get("model"), MODEL))
        return 2
    print("source: %s" % src)

    fp = EC.basis_fingerprint()
    if fp != M.FINGERPRINT:
        print("the table in force (%s) is not this campaign's (%s)"
              % (fp, M.FINGERPRINT))
        return 2

    have, bridge = [], []
    for name in STAKED:
        rec = pot["species"].get(name)
        if rec is None:
            print("  %-4s not assembled yet" % name)
            continue
        got = rec["provenance"].get("basis_fingerprint")
        if got != fp:
            stale = os.path.join(outdir, "%s.json" % name)
            if os.path.exists(stale):
                os.remove(stale)
            print("  %-4s REFUSED: assembled under basis %s, current is %s"
                  % (name, got, fp))
            continue
        path, n, changes = EE.emit_pair(name, rec, outdir)
        cd = rec["diagnostics"].get("certified_significant_digits_min")
        note = ""
        if name in SP2.D1_BRIDGE:
            _mark_bridge(path, name)
            bridge.append(name)
            note = "   [D1 BRIDGE REFERENCE]"
        print("  %-4s %3d geometries -> %s   (>= %s certified significant "
              "digits)%s" % (name, n, os.path.basename(path), cd, note))
        for c in changes:
            print("         %s" % c)
        have.append(name)

    owed = [x for x in STAKED if x not in have]
    man = {
        "model": MODEL,
        "basis_fingerprint": fp,
        "basis": ("STO-3G, Z = 1..18, s and p shells only. The first row is "
                  "ELEMENTS-1's table by reference; the second row is 24 "
                  "exponents transcribed from the engine's elements.rs and "
                  "checked against it by parsing that file "
                  "(test_basis_matches_engine.py)."),
        "no_d_shell": ("No declared species below argon carries a d shell, and "
                       "the prereg's own feasibility map proves it: Ar2 is ONE "
                       "determinant only if argon has 9 basis functions. The "
                       "engine defines ShellKind::D3 and md.rs implements "
                       "l = 2, but nothing at or below Z = 18 uses either."),
        "scope": {
            "max_Z": 18,
            "why_it_matters": ("The engine declares elements above argon. This "
                               "referee does not, so for any species above it "
                               "there is NO referee value -- and a gate reading "
                               "'the engine matches the referee' is VACUOUSLY "
                               "true for a pair it cannot grade. Check this "
                               "bound before reading a pass."),
        },
        "atoms": "atoms.json (H through Ar, referee-grade, dual route)",
        "staked_eight": STAKED,
        "staked_eight_note": ("the species MIXTURES1_PREREG.md's gate R2 names. "
                              "present + owed is this set, always: a pair may "
                              "move from present to owed, it may not leave "
                              "both. Coverage read purely from a manifest can "
                              "shrink silently when a file goes missing, "
                              "because the thing the gate checks against shrank "
                              "with it."),
        "pairs_present": have,
        "pairs_owed": owed,
        "negatives": {
            "pairs": SP2.E2_UNBOUND,
            "stake": ("gate E1: NO well deeper than 1e-4 hartree anywhere on "
                      "the staked grid. Branch (b) is investigate, never "
                      "massage."),
        },
        "d1_bridge_references": bridge,
        "d1_bridge_note": ("S2 and SiO are the overlap species of gate D1. "
                           "Their files carry a d1_bridge_reference block "
                           "saying so. The DMRG route is graded against them "
                           "at 1e-8; these values are exact-in-model at 50 "
                           "digits, so a disagreement is the DMRG's."),
        "grid_rule": ("Every grid is a function of one declared number per "
                      "pair (R_ref, tabulated experiment, CONTEXT only under "
                      "M-ONE-MODEL-DELTA) and a fixed rule whose multipliers "
                      "were calibrated on ELEMENTS-1's closed design choices. "
                      "No energy this campaign computed enters a grid. Each "
                      "file carries grid_provenance and the emitter regenerates "
                      "the grid from it."),
        "grading": {
            "E_hartree": ("referee-grade for every emitted pair; the declared "
                          "bound is max(Temple, measured route A vs route B)"),
            "F_hartree_per_bohr": ("grade varies per pair; read "
                                   "derivative_provenance.route and gate "
                                   "against the declared uncertainty, not a "
                                   "flat bound"),
            "E2_hartree_per_bohr2": "as F",
        },
        "rules": [
            "no column declares a zero uncertainty; a zero is a missing bound "
            "that passes a presence check",
            "every number is a plain fixed-point decimal string, never a JSON "
            "number and never exponent notation",
            "R_grid_bohr is authoritative and is an exact short decimal, so "
            "the published R IS the R the energy was computed at",
            "a sparse exact referee is a referee; a dense approximate one is "
            "not. Where a pair is expensive it carries FEWER points, never "
            "cheaper ones.",
        ],
    }
    with open(os.path.join(outdir, "manifest.json"), "w") as f:
        json.dump(man, f, indent=1)
    print("wrote manifest.json  (present %s | owed %s)"
          % (have or "-", owed or "-"))
    if bridge:
        print("D1 bridge references marked: %s" % ", ".join(bridge))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
