"""The MIXTURES-1 staked species, their grids, and the rule that makes a grid.

EVERYTHING HERE IS STAKED BEFORE ANY ENERGY IS COMPUTED.  That is the whole
point of the file, so it is worth being precise about what "result-blind" does
and does not mean here.

WHAT GOES IN.  Each pair declares ONE number, `R_ref`, the tabulated
EXPERIMENTAL equilibrium separation (or the van der Waals minimum for the two
negatives).  It is a CONTEXT input under the campaign's M-ONE-MODEL-DELTA
misfit: experimental values are labelled context and no gate is scored against
them.  Its only job is to set the SCALE of a grid, because a grid that runs from
0.3 to 10 bohr is right for H2 and useless for Ar2.

WHAT DOES NOT GO IN.  No energy this campaign computes, and no bond length this
campaign computes.  Where the in-model minimum falls, how deep it is, and
whether there is one at all are decided by the energies afterwards; gate E1 is
staked on exactly that for Ar2 and NeAr and would be worthless if the grid had
been placed to make it come out.

THE RULE IS A FUNCTION, NOT A LIST.  Both windows below are computed from
`R_ref` by a fixed formula, so the grid can be REGENERATED by anyone from
`R_ref` and the rule.  This is the guard ELEMENTS-1 added after the fact
(`grid_provenance`: the emitter rebuilds the grid from the file's own declared
parameters and refuses the file if it differs), adopted here from the start
rather than retrofitted.  The multipliers were fixed by reading what ELEMENTS-1
had already staked -- across its seven bound species the window is [0.73, 0.89]
x R_ref at the low end and [1.04, 1.39] x R_ref at the high end -- and rounding
outward to one rule that contains all seven.  So the rule is calibrated on a
CLOSED campaign's design choices, not on this campaign's results.

DENSITY IS A COMPUTE DECISION AND SAYS SO.  The number of knots per pair comes
from the MEASURED cost of one geometry (see `_cost_probe.py` and
`COST_MEASURED` below), never from where anything interesting is expected to
be.  The response to an expensive pair is FEWER points, never cheaper ones:
every emitted point is the same exact-in-model full CI at the same 50 digits,
dual-route and certified.  A sparse exact referee is a referee; a dense
approximate one is not.
"""
from mpmath import mpf

import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
if os.path.join(HERE, "elements1") not in sys.path:
    sys.path.insert(0, os.path.join(HERE, "elements1"))

import curve                                                  # noqa: E402
import basis2                                                 # noqa: E402

BOHR_PER_ANGSTROM = mpf("1.8897261254578281")   # CODATA 2018, a definition here

# Symbols for Z = 1..18.  ELEMENTS-1's ELEMENT_SYMBOL stops at neon.
SYMBOL = {1: "H", 2: "He", 3: "Li", 4: "Be", 5: "B", 6: "C", 7: "N", 8: "O",
          9: "F", 10: "Ne", 11: "Na", 12: "Mg", 13: "Al", 14: "Si", 15: "P",
          16: "S", 17: "Cl", 18: "Ar"}
Z_OF = {v: k for k, v in SYMBOL.items()}

# --------------------------------------------------------------------------
# THE GRID RULE, in staked multipliers of R_ref.
# --------------------------------------------------------------------------
# ELEMENTS-1's seven bound species, as staked there:
#     H2   rmin/R_ref 0.26  rmax/R_ref 8.53  well [0.85, 1.88]
#     LiH  0.40  4.64  [0.73, 1.39]
#     Li2  0.51  3.56  [0.83, 1.39]
#     HF   0.52  5.77  [0.81, 1.39]
#     N2   0.52  3.36  [0.67, 1.04]
#     F2   0.60  3.75  [0.75, 1.35]
#     CO   0.66  4.22  [0.89, 1.36]
# One rule containing all seven, rounded outward:
BOUND_RULE = dict(rmin=mpf("0.50"), rmax=mpf("4.50"),
                  well_lo=mpf("0.65"), well_hi=mpf("1.45"))
# The two negatives were staked wider and lower, because the question there is
# not where a minimum is but whether the curve ever gets below dissociation:
#     He2  0.21  2.14  [0.62, 1.43]
#     Ne2  0.31  2.05  [0.77, 1.54]
NEGATIVE_RULE = dict(rmin=mpf("0.20"), rmax=mpf("2.20"),
                     well_lo=mpf("0.60"), well_hi=mpf("1.55"))

RULE_DECIMALS = 2       # rmin/rmax/well are snapped to exact 2-decimal strings


def _snap(x):
    """An exact short decimal, so the published R IS the R computed at."""
    return curve.dec_str(mpf(x), RULE_DECIMALS)


def window(R_ref_bohr, negative):
    r = mpf(R_ref_bohr)
    d = NEGATIVE_RULE if negative else BOUND_RULE
    return dict(rmin=_snap(r * d["rmin"]), rmax=_snap(r * d["rmax"]),
                well=(_snap(r * d["well_lo"]), _snap(r * d["well_hi"])))


# --------------------------------------------------------------------------
# THE STAKED SPECIES.
#
# R_ref_angstrom is CONTEXT (tabulated experiment), used only for scale.
# negative=True means gate E1 is staked on this pair: no well deeper than
# 1e-4 hartree anywhere on its grid.
# --------------------------------------------------------------------------
STAKED = {
    "Cl2":  dict(a="Cl", b="Cl", R_ref_angstrom="1.988", negative=False),
    "S2":   dict(a="S",  b="S",  R_ref_angstrom="1.889", negative=False),
    "Ar2":  dict(a="Ar", b="Ar", R_ref_angstrom="3.760", negative=True),
    "HCl":  dict(a="H",  b="Cl", R_ref_angstrom="1.275", negative=False),
    "ClF":  dict(a="Cl", b="F",  R_ref_angstrom="1.628", negative=False),
    "NaH":  dict(a="Na", b="H",  R_ref_angstrom="1.887", negative=False),
    "SiO":  dict(a="Si", b="O",  R_ref_angstrom="1.510", negative=False),
    "NeAr": dict(a="Ne", b="Ar", R_ref_angstrom="3.490", negative=True),
}

# The E2 ordering hypothesis, deepest first, exactly as the prereg states it.
# N2 comes from ELEMENTS-1's table, so E2 is scored ACROSS the two campaigns.
E2_ORDER = ["N2", "SiO", "HCl", "ClF", "S2", "Cl2", "NaH"]
E2_UNBOUND = ["Ar2", "NeAr"]

# The D1 bridge's referees: the two species where exact FCI and q8-mps DMRG
# overlap, per the frozen prereg.
D1_BRIDGE = ["S2", "SiO"]


def R_ref_bohr(name):
    return mpf(STAKED[name]["R_ref_angstrom"]) * BOHR_PER_ANGSTROM


def ndet(name):
    """The determinant count -- a property of the declared model, not a choice.

    This is the quantity the prereg's feasibility map is stated in, and it is
    recomputed here rather than quoted so the map cannot drift from the basis.
    """
    from math import comb
    d = STAKED[name]
    n = basis2.NBF[Z_OF[d["a"]]] + basis2.NBF[Z_OF[d["b"]]]
    ne = Z_OF[d["a"]] + Z_OF[d["b"]]
    na = (ne + ne % 2) // 2
    return comb(n, na) * comb(n, ne - na), n, ne, na, ne - na


def nnz_estimate(name):
    """Nonzero Hamiltonian elements -- the quantity that actually sets the cost.

    The working-precision matvec walks every one of them, so THIS and not the
    determinant count is what a grid's density has to be budgeted against.  For
    N2 (ndet 14400) it predicts 8,784,000 against the 8.8e6 the crate's own
    comment records, which is the calibration that licenses using it.
    """
    from math import comb
    nd, n, ne, na, nb = ndet(name)
    v = n - na
    per = 1 + 2 * na * v + 2 * comb(na, 2) * comb(v, 2) + (na * v) ** 2
    return nd * per


GRID_DPS = 60


def grid_spec(name):
    d = STAKED[name]
    w = window(R_ref_bohr(name), d["negative"])
    return dict(name=name, Z1=Z_OF[d["a"]], Z2=Z_OF[d["b"]],
                R_ref_angstrom=d["R_ref_angstrom"],
                R_ref_bohr=curve.dec_str(R_ref_bohr(name), 6),
                rule="NEGATIVE" if d["negative"] else "BOUND",
                negative=d["negative"], **w)


if __name__ == "__main__":
    print("MIXTURES-1 staked pairs -- grids from R_ref and the rule alone\n")
    print("%-5s %-7s %-9s %-7s %-7s %-15s %-12s %-14s"
          % ("pair", "Z1/Z2", "ndet", "rmin", "rmax", "well window",
             "R_ref(bohr)", "nnz est"))
    for nm in STAKED:
        g = grid_spec(nm)
        nd = ndet(nm)[0]
        print("%-5s %-7s %-9s %-7s %-7s %-15s %-12s %-14s"
              % (nm, "%d/%d" % (g["Z1"], g["Z2"]), format(nd, ","),
                 g["rmin"], g["rmax"],
                 "[%s, %s]" % g["well"], g["R_ref_bohr"],
                 format(nnz_estimate(nm), ",")))
    print("\nE2 ordering hypothesis (deepest first): %s  >>  %s"
          % (" > ".join(E2_ORDER), ", ".join(E2_UNBOUND)))
    print("D1 bridge referees: %s" % ", ".join(D1_BRIDGE))
